### ISSUE TITLE
Mobile Menu 

### ISSUE THREAD

**Issue by arpita-addweb** [saurabhd/hk_realestate#1]
**Site Area** : Mobile ,    **Priority** : High  

**Description :**
Find a solution for a mobile menu that contains main and footer menu and is cache able.

**Comment by vivek-addweb** [comment]
Hi Rainer

Mobile menu design is pushed on develop branch. Mobile menu block combines header and footer menu. Please do following : 
go to "admin/structure/block" and assign "Mobile Menu" block to "Navigation bar" region

**Comment by heliogabal** [comment]
Hi Vivek, 

I really like the menu style, but there still seems to be a bug with the click function. When I first click the menu burger icon, the menu opens but doesn't stay open but closes back directly and the icon is switched to the close x. Now I can click the x icon and open the menu just fine, but icons are toggled, so I see the x when I should see the burger and vice versa. 

I looked at the script, and I think you don't need another  `$(document).ready(function() {` as it is already inside the Drupal.behaviors.BearScripts. But that didn't solve the problem, so there must be something else.

I tested this on my mobile (Moto G) and chrome dev tools. 

![mobile-menu-toggle-bug](https://cloud.githubusercontent.com/assets/389844/14555490/3abedbe8-02f3-11e6-8bf9-bfdec1225095.png)

**Comment by heliogabal** [comment]
The mobile icon should also align with the other icons (don't know why they don't show up here, still have to check), so you should get rid of the 
`@media (max-width: 1024px)
.meanmenu-reveal {
    margin-right: 40px;
}`

**Comment by vivek-addweb** [comment]
I will check burger icon click issue.

**Comment by heliogabal** [comment]
Hi Vivek, 

please make sure to focus on this issue and #2 first, as right now, the mobile version is unusable on the live site, so this should be the first thing fixed if possible.  

Thanks!

**Comment by heliogabal** [comment]
Hi Vivek, 

Great, I tested it, and now it's ready for production. I adjusted the position of the leaflet zoom, scale and attribution and of the service menu icons with my last commit, can you merge this in the master branch at the same time, or do I have to do it?
