### ISSUE TITLE
CSS 3 transition when toggling the search box to provide a visual connection between search icon and box

### ISSUE THREAD

**Issue by arpita-addweb** [saurabhd/hk_realestate#10]
**Site Area** : search box ,**Priority** : Medium 

**Description** :
Something like the 'transfer' jquery ui effect. Or http://zurb.com/forrst/posts/CSS3_Open_a_popup_with_a_transfer_effect-NxK Can be creative, the client would love to have some "wow" animations where it makes sense...

**Comment by heliogabal** [comment]
Hi Vivek, 
I can't really see any new toggle animation? Is that visible on Desktop, or is it basically #2 so just on mobile for now? Do you need more or better description for this?

**Comment by vivek-addweb** [comment]
Hi Rainer,
I have used slide Toggle effect for Search box same that is working in Mobile  menu.
Do you want to change toggle effect for Search box?

**Comment by heliogabal** [comment]
Hi Vivek, 
ah, now I see it. No, it's fine like that. I can close this now. Thanks for your work! So how does this work now? I close this issue, and you merge it into the master branch? It's the first time I'm working like this, excited!

**Comment by heliogabal** [comment]
I discovered some kind of regression still... on the frontpage the search toggles fine, but on the buy and subpages, the search slides up, but then slides immediately down again, so the toggle doesn't work. As I remember, this used to work already. If that is fixed, we can close this as well.

**Comment by heliogabal** [comment]
Seems fixed now? Working on the dev site, but unfortunately, on live it doesn't. So please merge with master so I can fix that on live site as well.
