### ISSUE TITLE
#social add newsletter registration to inquiry and contact forms

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#12]
The client wants to start building a mailing list, therefore he needs visitors to opt in on the website. It is not decided yet what mailing list software is going to be used in the end, so the solution should be flexible enough to export the subscriber list and use it elsewhere, or provide the best mailing solution within Drupal later on. I think simplenews or mailchimp would be the most viable options, but I haven't looked into their collection and export capabilities. 

So please have a look and recommend the best solution for this scenario. There should be checkboxes on the inquiry and contact forms, saying "I want to be informed on future offers that might be comparable", between the message field and the send button. The checkbox musn't be checked.

**Comment by darshi-shah** [comment]
Hi Rainer,

Simplenews would be better. It allows to send newsletter from site itself. It uses mime mail so HTML emails are also supported. 

In future,  if we decide to use mailchimp for example, we can do that with simplenews.

Checkboxes on inquiry and contact form can be done as well.

Let me know when we need to start working on this.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,
that sounds good, I'm using Mime Mail already for transactional Emails, so let's use simplenews then. 

For now, only the collection of Email addresses will be needed asap, as it might take a while until the first Newsletter is sent. So you can start with that right away. 

Take note that for Email sending, I had to switch from Mandrill to Amazon SES on production, but that is not yet reflected on develop.

**Comment by darshi-shah** [comment]
Hi Rainer,

Please do following : 

1 - take pull

2 - enable simplenews module

3 - go to "admin/config/services/simplenews" and set configuration as per this image : http://i.share.pho.to/fcb2838f_o.png. 

4 - go to "admin/config/services/simplenews/settings" and set configuration as per images : 
    - http://i.share.pho.to/86a675b3_o.png (newsletter)
    - http://i.share.pho.to/760cf659_o.png (subscription)
    - http://i.share.pho.to/f9b78bf5_o.png (Send mail)

5 - set user permission. allow all users to "Subscribe to newsletter".

6 - clear cache and test the functionality. 

Let me know any questions in this.

Thanks,
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,

tested it, and seems to work. Have to further test and check with the legal advisor if it's ok like that. If I fill out the form as anonymous user, there is a second email field:
![2-zimmer altbauwohnung mit balkon herbert kohlmeyer immobilien gmbh - mozilla firefox private browsing _001](https://cloud.githubusercontent.com/assets/389844/15184563/f833603e-1795-11e6-84b7-b9625647b9a2.png)

There should of course be only one, and it has to be synchronized with CRM Core, like the mandatory email field, so duplicates can be merged.

By the way, if I fill out a second inquiry and don't check the box, I am not getting unsubscribed again, I hope?

Thanks for explaining.

**Comment by darshi-shah** [comment]
Hi Rainer,

The second email was for anonymous user. I have removed second email field. 

Also, if you fill inquiry form second time and leave newsletter checkbox unchecked, you dont get unsubscribed .

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,

ok, thanks. I just realized that the field "Inquiry for" disappeared from the form somehow. On the live site, because it is now a multi-valued field, the field is there, but styling doesn't match any longer. Can you please check why it is not there on dev and adapt the styling so it looks like before (hide button and second field, drag handler and background colour)? Also, even on the German page, the translation for Inquiry for (Anfrage für) is not shown, although it exists. Maybe it's better to create a separate issue for that to better keep track of these tasks.

![selection_002](https://cloud.githubusercontent.com/assets/389844/15247563/622f96f8-1915-11e6-9ac2-1505534836dc.png)

**Comment by darshi-shah** [comment]
Hi Rainer,

This seem separate from newsletter issue. Can you please create new issue for this and close this one please ?

I will check this on local and dev.

Thanks
Darshi
