### ISSUE TITLE
#social Twitter: possibility to create tweets from new objects

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#14]
New objects should have a checkbox as a publishing option to send a tweet about the offer. There should be a standard message created from the object title and Text Karten-Popup field, with the option to write another message instead. And of course a link back to the object page on the website.

**Comment by darshi-shah** [comment]
Hi Rainer,

Please let us know which twitter account to use for this.  We will need credentials.

To confirm, admins will check this checkboxe and tweet will be sent.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 

I sent you the login on skype. Yes, users of the group admintooluser shall have permission to check the Twitter checkbox and to modify the pregenerated message, that will get tweeted once the object gets published.

**Comment by darshi-shah** [comment]
Hi Rainer,

I got no credentials on skype. If would be good if you add them here.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Twitter credentials

**Comment by heliogabal** [comment]
No good idea to post the password, as the repository is public...

**Comment by darshi-shah** [comment]
Comment updated. Sorry about this.

**Comment by darshi-shah** [comment]
Hi Rainer,

Please follow below steps :

1 - take pull

2 - Enable oauth, Twitter, Twitter actions,Twitter Last Tweet Field, Twitter Post, Twitter Signin

3 - go to https://apps.twitter.com/app/12339123/. This is twitter app. change callback URL to have HK live site callback URL, For example, http://herbert-kohlmeyer.com/twitter/oauth

4 - go to  admin/config/services/twitter/settings

5 - under oauth settings, add keys from twitter and save

6 - go to admin/config/services/twitter/post

7 - select "objekt" in node types and check "Post to Twitter by default"

8 - go to admin/config/services/twitter and click on "GO TO TWITTER TO ADD AN AUTHENTICATED ACCOUNT"

9 - authorise the app, you will see twitter account added.

Upon publishing content of type "objekt" tweet will be sent. Tweet is not sent of objekt is not published.

Let me know any quesions in this.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,
Ok, great! I tried on the addweb.dev site and posting is working. Now, the standard is set to always post a new object, but if I uncheck the box on the "Post to twitter.com" tab, no tweet is sent? Then we would be finished with that issue, I guess. We just need a way to prevent objects from being posted that are not that interesting.

**Comment by darshi-shah** [comment]
Hi Rainer,

You can keep  "Post to Twitter by default" unchecked in step 7. Tweets will be sent automatically but you get an option on Objekt to send them if you want.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 

ok, thanks, so I think we can close this as well and merge to master?
