### ISSUE TITLE
#touch Prevent keyboard on search selects

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#15]
When I look at the mobile and tablet version, once I try to select something from the search box, the OS keyboard opens, even though I don't need it and it overlays the form. Makes it really hard to select something. 

So please find a way to prevent the keyboard from showing up when searching. Of course it has to come up when making an inquiry or filling out the contact form. I found several solutions on stackoverflow, either using blur or deselected on the input fields, so it should be possible either with JS or hook_form_alter. Not sure what the best solution is.

**Comment by darshi-shah** [comment]
Hi Rainer,

I tried checking this on http://addweb.dev.drupalforgood.eu but search is not working on this properly on mobile device for this. Let me know on which site I can check this.

Thanks,
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
I did a git pull yesterday there but didn't check, so right now js is not working. I'll check and let you know once it's working again.

**Comment by heliogabal** [comment]
Hi Darshi, 

now you can check. I cleaned up too much on my latest commit, readded now. Sorry for the delay.

**Comment by darshi-shah** [comment]
Thanks Rainer

**Comment by darshi-shah** [comment]
Hi Rainer,

js is added for this. Also, Search toggle effect that we added previously was removed so added that back as well.

Let us know once this is up on staging site so we can check there.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 

it's pulled, but I think you have to add some prevent default to the js, otherwise, the dummy-link is followed. I can't see the inputs at all, only the box is toggled.

**Comment by darshi-shah** [comment]
Hi Rainer,

prevent default is added in js.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 

Ok thanks, so now we stay on the page when toggling the search. The initial issue is still kind of pending? Is the readonly attribute reliable on different platforms? As I said before, on my mobile Chrome I don't see the inputs, so I can't check. Is it supposed to be working yet?

**Comment by vivek-addweb** [comment]
Hi Rainer

Issue is resolved for mobile view. You will be able to see input fields now.

**Comment by heliogabal** [comment]
great, it's working now! ... at least for the homepage. On buy, I don't get any search box to toggle... is it only me?

**Comment by vivek-addweb** [comment]
Hi Rainer
Issue is resolved for mobile view on Buy page.
