### ISSUE TITLE
Create immobilienscout24 synchronization

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#17]
The client should have the choice to publish apartments from the website to the biggest German real estate portal immobilienscout24.de 

If apartments are published on immoscout, changes on the website should also be synchronized to immoscout.

If apartments are depublished from the website, they should also be depublished from immoscout.

The immoscout APIs can be accessed via a sandbox, you can apply for access here: http://api.immobilienscout24.de/get-started.html I will apply for productive access connected to the H+K account next week. 

Let me know if you need more information.

**Comment by darshi-shah** [comment]
Hi Rainer,

Immobilienscout24 has 3 different use cases.  Please confirm that we will be "Content Partner" with them.

I am currently going through "Search API" : http://api.immobilienscout24.de/our-apis/search.html

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,
I think what we're looking for is the import-export API to be able to post Apartments from Drupal to Immoscout: http://api.immobilienscout24.de/our-apis/import-export.html

They describe the process there, don't know if that means to become a "content Partner".

**Comment by darshi-shah** [comment]
Hi Rainer,

I will check import-export API. 

Content partner was here : http://api.immobilienscout24.de/get-started.html and search API was mentioned as useful API in it. 

Thanks
Darshi

**Comment by heliogabal** [comment]
I see. I found this page quite confusing, but in my understanding of it, first use case is for creating your website with content that you have already on your immoscout account, second is the one that applies to us where you want to create content on immoscout from another source, and the third is if you want to use immoscout content from different sellers for your own portal or custom development / app. So it would be Managment app, whatever that is supposed to mean...

**Comment by darshi-shah** [comment]
Hi Rainer, 

I  went through available docs. Let me know when you have credentials.  I can start looking into how API will work with the site.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
you should be good to go with the sandbox account, credentials are only neccesary to connect with the live site. You can apply for one filling out the email form described here: http://api.immobilienscout24.de/get-started.html I can't do this right now as I'm still waiting for my laptop being repaired.

I'll see to a full API access next week.

**Comment by darshi-shah** [comment]
Hi Rainer,

I have applied for sandbox account. I will let you know once I receive a reply.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer , 

I haven't received any reply from immobilienscout24 for sandbox account . Please let me know how to proceed with this

Thanks
Darshi

**Comment by heliogabal** [comment]
Immoscout contacted, will have to wait for answer.

**Comment by heliogabal** [comment]
still no answer from them? If so, I'll try myself as well to get one.

**Comment by darshi-shah** [comment]
Hi Rainer, 

No reply so far.

Thanks
Darshi

**Comment by heliogabal** [comment]
I also applied with their crappy email form now, hope to get one soon. I have productive API access already, that went very fast... but we need to test in sandbox first.

**Comment by darshi-shah** [comment]
Okay. Thanks.

**Comment by heliogabal** [comment]
Do we have sandbox access by now? Can you estimate how much time this is going to take? I will have to confirm with the client if this should be prioritized now or be further delayed, but it would be good to know about how much money we are talking here. 

Thanks!

**Comment by darshi-shah** [comment]
Hi Rainer,

I had sandbox access but  its not working currently. I have requested access again. I will let you know when I have them.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

I finally got sandbox access working. To estimate, we need to do a demo with new drupal install. I will keep you posted on how it goes.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
well of course, take some time to estimate. Just don't spend too much of it, the client gets a little nervous about expenses right now and understandably wants to know upfront what it will be.

**Comment by darshi-shah** [comment]
Hi Rainer,

We have spent 4 hours so far on this to get API keys and access and testing this on their site. Please do let us know how many more hours we can spend on this before estimation. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Would 4 additional hours be enough? Then go for it. Would be good to know by Wednesday how much your estimate is.

**Comment by darshi-shah** [comment]
4 hours is fine. We will provide estimate on Wednesday.

**Comment by heliogabal** [comment]
Great!

**Comment by darshi-shah** [comment]
Hi Rainer,

We would need 1 week to do this. Please let us know if we can start this.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
please hold that, as we are in a strategic discussion about the usage of immoscout, so it might take a while before we move on this. 

thanks for the estimate!

**Comment by heliogabal** [comment]
After all, we won't need this in the foreseable future, as propstack already has an export function to immoscout. So closing this now.
