### ISSUE TITLE
CRM - autocomplete search

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#20]
Fast autocomplete search to find Contacts. When you click on a search result, you are taken to the Contact page (Mockup 2).

The search should be based on a new SOLR search index, possible module candidates are search_api_live and search_api_autocomplete. There is an issue in the cue to merge the two modules together, but that needs work: https://www.drupal.org/node/1567234 

Here's a tutorial how to get this to work (we probably don't need the search pages module): http://www.stevepolitodesign.com/blog/create-live-search-results-search-you-type-drupal 

If SOLR is too much work, maybe we can base version 1 on search_autocomplete and create SOLR version later.

**Comment by darshi-shah** [comment]
Hi Rainer,

The code for this is pushed on git in new branch called "hkcrm".

You need to enable hk_crm feature. "Buyer" role is already created. Assign this role to user to see dashboard.  Dashboard is on user page (user/id/dashboard) .  

Search redirect is working. 

Let me know any questions regarding this.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

The code for this is pushed on git in new branch called "hkcrm".

You need to enable hk_crm feature. "Agent" role is already created. Assign this role to user to see dashboard.  Dashboard is on user page (user/id/dashboard) .  

Search redirect is working. 

Let me know any questions regarding this.

Thanks
Darshi

**Comment by heliogabal** [comment]
We changed the dashboard url to /search. The search redirect is somehow still not working for me (although it worked before).

**Comment by heliogabal** [comment]
working now. closing...!
