### ISSUE TITLE
CRM Dashboard - unclaimed leads table view

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#21]
Table of Unclaimed Leads that an Agent can take action on to assign the buyer to himself. That means he is ultimately responsible for this client (client owner), but other agents can still interact with the contact.

An entityreference field has to be created on the crm core contact type to create the connection between contact and the owner / responsible agent of that contact. It should be filled via Entity reference prepopulate with the acting agent. 

There is already a View called CRM Anfragen (CRM Core Aktivität) that can be repurposed for that matter. The existing pages would become the Office manager views in the second phase, the unclaimed leads view can be added there.

View needs following fields: Apartment image, Inquiry for, Inquirer, Message, Action, Date. 

Actions should open in a lightbox and provide the following (in this order):
- Email activity
  -- CRM Core activity email form that gets recorded
  -- Allow to write a personal message that gets sent as email to the contact
  -- Phase 2 (to be kept in mind as possible extension of functionality): allow to choose preconfigured templates that can be customized to be sent as email
  -- Document request
- Phone call activity
  -- CRM Core activity phone call that gets recorded
- Note
  -- general notes an agent can take concerning a buyer.
- Calendar entry / meeting (postponed until agent central)
  -- CRM Core calendar activity that gets published on the agents calendar and the office manager calendar
  -- Phase 2: Send email to contact with the calendar date. Maybe have a client calendar with his dates on the buyers profile.
- To-do activity / task (postponed until agent central)
  -- CRM Core activity task with agent and buyer references that gets recorded and shown on the agents to-do-list.

![unclaimed_leads_table](https://cloud.githubusercontent.com/assets/389844/16002664/1b9fa53c-3159-11e6-9d7b-8ed0a0a0dc55.jpg)

**Comment by darshi-shah** [comment]
Hi Rainer,

Code is pushed in "hkcrm" branch. You need to revert  hk_crm feature. Work is in progress for this.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
I reviewed the table, and have some (hopefully) minor suggestions to finish it: 
- The "inquiry for" column should also show Objekt ID and a - followed by the apartment no. (BBP02-04), because the titles are often too similar to really see what apartment it is. I used the apartment live results view mode for that to try, don't know if that is used for something else. (must have for launch)
- Inquirer column: I think it's save to show only one result (the second one) of the participants field here, to get rid of the Mitarbeiter. Then, get rid of the profile image title, and I'm not sure if we need the profile image here at all (it won't be filled for a lot of people first anyway and takes some attention from the apart pic). (must have for launch)
- Actions column: Can we get some (translatable) titles so the icons are explained when hovered? I think that would add to the UX without much effort. (would be good for launch)
- When clicking on the icons, the activity add form is shown. You already prepopulated the inquiry field, can the recipient (with the contacts email address) and participants fields (with contact and acting agent) also be prepopulated? (if timeframe allows, otherwise I'll explain it comes later)
- For the email activity, title should become the email subject, the notes field the email body. (if timeframe allows, otherwise I'll explain it comes later)
- For the Phone call activity, the title could probably get autogenerated with a standard "Phone call" or "Phone Call - Date" I think. (if timeframe allows, otherwise I'll explain it comes later)

**Comment by heliogabal** [comment]
I've seen that you already worked on this, some more things I discovered:
- Inquirer should show 1 value, starting with 1, not 0. Otherwise, its always Ilka that is shown.
- I have no idea why, but all inquiries are shown twice in the table. I tried to apply distinct query setting, but that didn't help... WTF?
- The table should not only show inquiries but also Kontaktformular - basically everything that comes in through the website, so direct apartment inquiries and general contact form messages.

**Comment by darshi-shah** [comment]
Hi Rainer,

Code is pushed in "hkcrm" branch. You need to revert hk_crm feature.
1. Inquirer should show 1 value, starting with 1, not 0. Otherwise, its always Ilka that is shown.
   => Done
2. I have no idea why, but all inquiries are shown twice in the table. I tried to apply distinct query setting, but that didn't help... WTF?
   => Done
3. The table should not only show inquiries but also Kontaktformular - basically everything that comes in through the website, so direct apartment inquiries and general contact form messages.
   => Done
   =>Query: For inquiry we set image of apartment but contact form there is no any reference to apartment. so which image need to display on for contact form ?

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, very good. For the contact form image, just don't show an image if empty, like already done with the inquired apartment.

**Comment by heliogabal** [comment]
just have to get rid of the profile picture in the inquirer column, and don't show empty image, then I can close this. Still would have to work on the details of the action buttons, but I think it is better to create a new issue for that.
