### ISSUE TITLE
CRM - create / finalize CRM Core contact types

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#23]
We need the following CRM Core contact types: 
- Individual
  -- Prospective buyer
  -- Owner
  -- Agent
  -- Business partner
- Connection
- Company

For the individuals, we need the following fields: 
- profile picture (from social login or upload)
- address
- email (multiple entries, select primary email)
- phone (multiple entries, select primary phone)
- job title
- languages
- birthday
- other (free text field)
- responsible agent (entityreference) 
- secondary agent (entityreference)
- company (entityreference with dialog)
- connection (entityreference with dialog)

**Comment by heliogabal** [comment]
removing critical as we can probably change this later on? Need some comment on this, if that could be a problem once we're in production... Right now, we still have two distinct contact types for buyer and agent, these should get combined and distinguished by a taxonomy rather than a distinct contact type.

**Comment by darshi-shah** [comment]
Hi Rainer,

We have added a new taxonomy called "Individual Type" which has following terms : 

-- Buyer
-- Seller
-- Agent
-- Business partner

We are using this taxonomy in "Kunde(individual)" contact type to differentiate the contact types.  

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
very good. We should indeed rename Kunde back to Individuum, so it becomes more clear that this is the general contact for individuals that gets further differentiated via taxonomy. Of the individual types, Seller should be renamed to Owner, as I got explained that there might be owners in the database that don't want to sell (right now), but all the sellers are owner nonetheless...

Then we can clean up the mess and remove the Mitarbeiter (agent) contact type that I created prematurely.

Household should be renamed to Connection, and Organisation to Company. These should also be removed from the Create Contact Button, so there are only these items to under Create Contact: 

-- Prospective buyer
-- Owner
-- Business partner
-- Agent
(this should open the add contact form with the matching taxonomy prepopulated).

Then, every individual should have a connection and company entity reference field with the autocomplete widget with edit, add and search activated from the entity reference dialog module, so existing companies or connections can be selected and new ones created right from there. 

We would have to see which individuals needs to have which entity reference visible in the end, but I think there could be cases where all of them are needed. For example, there could be agents from another company than H+K that would get access to certain apartments and contacts in the future, so they would need a company associated, Business partner could be a lawyer that works in a big law firm, owner could also be a representative of a company and even the prospective buyer could not be buying for himself but on behalf of a company...

We also need an additional field "secondary agent", because there should always be two agents that know about the contact. Just a simple entity reference to an agent.

**Comment by darshi-shah** [comment]
Hi Rainer,

You will need to rename the contact types manually. 

We have added required fields for connection and company in individual contact type. Please do let us know how we are going to implement connections and company in activities. As of now, we have taken entity ref for this.

We have also added "Secondary agent" field. This agent assignment is manual as of now. 

We have also made changes in "Create Contact "  menu as mentioned in your comment. 

Let us know any changes in this.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
contact types were already renamed, only had to translate them. Working.

Where do we need connections and companies in activities? Aren't they just for contacts? Note: we agreed on skype to postpone use of connection and compannies.

Thanks for the secondary agent, but now, I see three agent fields - primärer Ansprechpartner (that should be the responsible agent), responsible agent and secondary agent. So no need for the extra responsible agent field, and the secondary agent is fine to be assigned manually, but it needs to be restricted to agents, then it can be a simple dropdown.

Create Contact menu is fine.

**Comment by heliogabal** [comment]
Hi Darshi, 
contact types were already renamed, only had to translate them. Working.

Where do we need connections and companies in activities? Aren't they just for contacts?

Thanks for the secondary agent, but now, I see three agent fields - primärer Ansprechpartner (that should be the responsible agent), responsible agent and secondary agent. So no need for the extra responsible agent field, and the secondary agent is fine to be assigned manually, but it needs to be restricted to agents, then it can be a simple dropdown.

Create Contact menu is fine.
