### ISSUE TITLE
CRM - Saved search

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#25]
Hi Darshi, 

I'll sum up here how the saved search should ideally work: 
- Agent can search and gets immediate list of matching results. Once the search is sufficiently defined, he can save the search with the "Save search" button.
- The search should be saved for the acting agent with a reference to the buyer the search is saved for. 
- The agent should get the new result email for every new match for every client that has a saved search. Something like "New matching apartment found for buyer X. Please check the contact page of the buyer to send him/her the new offering."
- the saved search would be loaded whenever the contact page is watched, so you can see the last saved search
- if you click the save search button again, a new saved search is created that replaces the previous one. Ideally, the agent or his supervisor would still be able to see the different revisions of the searches, so we have an audit trail of search activities. But that's just if it is very easy to provide (in the future).

**Comment by heliogabal** [comment]
This seems to work as outlined? Setting to check therefore.

**Comment by darshi-shah** [comment]
Hi Rainer, 

Its currently showing search criteria from latest saved search regardless of contact and agent. Apart from that rest of things are in place. We are working on making this contact specific.

Thanks,
Darshi

**Comment by heliogabal** [comment]
is this contact specific now? What about the email to the agent when a new match arrives? What about the revisioned saved searches?

**Comment by heliogabal** [comment]
What's the status on this?

**Comment by darshi-shah** [comment]
Hi Rainer,

Following is done in saved search: 

1 - Agent can save search for contact by clicking on "Save search" button. This saved search is assigned to user to who initially save it. Agents can see saved searches on their profile.

2 - Saved search is contact specific. All agents can see saved search when they open contact page.

3 - When new matching apartment is available, agent receives email notification. Email consists new apartment link along with saved search link. This email is sent to email id saved on user profile associated with agent. We are unable to add contact link to this email. The below is example of notification email sent to agent. 

> addweb,
> 
> There are new results for your saved search on Herbert + Kohlmeyer Immobilien GmbH:
> 
> New results for search “Gespeicherte Suche”:
> 4-Zimmer DG-Wohnung (http://addweb. dev.herbert-kohlmeyer.com/node/3741)
> 
> You can configure your saved searches at the following address:
> http://addweb. dev.herbert-kohlmeyer.com/user/1362/saved-searches
> 
> – Herbert + Kohlmeyer Immobilien GmbH team

4 - Saved search supports revisions. 

We have checked this on dev site. Let us know about any changes/ feedback on this please.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
I tried to test the saved search, but I'm not seeing all the fields and can't select anything from the existing fields. See:
![saved_search_missing_fields](https://cloud.githubusercontent.com/assets/389844/18744707/62e6aea8-80bf-11e6-8544-9df64ab57efd.png)

probably I have to revert some more, did so with hk_crm, but that didn't help. Any hints?

**Comment by darshi-shah** [comment]
Hi Rainer, 

This has been fixed. Please revert hk_search feature.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
thanks, much better now ;-) I tested the saved search, and it works quite well. 

Only thing that we have to solve somehow, is to make sure the agent knows to which contact that search belongs. If there can't be tokens directly in the mail, maybe we can save the saved searches with the name of the contact as saved search name? I can see that you can edit the name of the saved search on the page, so it should be possible to set it programmaticaly? 

Then it would be clear and obvious on the saved search page which search belongs to which contact, and the contact link is also right there...

Going from there, it would be even better if we could also incorporate (some) search parameters in the name, for being able to distinguish two searches for the same contact. 

If we can then have links to the different saved searches under the save button in the block, we would be almost reaching a good ux ;-) 

In the end, we should probably also make the saved searches page closer to the CRM Design and make it reachable for the agent without going through his emails, but that would be a later step that needs to be better prepared...

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are pushed on develop. Please revert hk_crm feature.

We implemented following: 

1 - We added saving search with custom name, agents can input the name they want in text box. This name will be displayed in email as well.

we can not add contact name or search parameters in search name automatically so instead we are allowing agents to add name so they can differentiate one search from another.

2 - We added a block containing links of saved search below save button. CSS is pending for this. 

Let me know your feedback on this and how to proceed with making saved search page having same look as CRM.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
very good. Can you go on with styling the block - the blue links really hurt the eyes ;-)

Would it be possible to also have disable edit and delete links directly on the block?

I still have to think about how to incorporate the saved search page better in the CRM hold on for that still.

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are done and pushed on develop branch. Cache clear is needed to see changes.

Thanks
Darshi

**Comment by heliogabal** [comment]
very nice. I wasn't able to translate the disable | edit | delete strings, is there anything special about them? 

Then, would it be possible to add a ?destination-parameter to these links, so after completing the action, the agent is redirected to the contact's page once again instead of landing on his saved-search page? This will confuse them, and there is no obvious way to get back where the agent was...

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are done and pushed in develop branch. Please check. You need to clear cache and add translations if not available.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
working good now. Can be pushed to master. Translations show up fine now without further work.
