### ISSUE TITLE
CRM - consistent CRM menu / header

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#26]
Not sure if I missed something after pulling, but I still see some things that need to be addressed: 

Dashboard
![auswahl_009](https://cloud.githubusercontent.com/assets/389844/16411438/59356b6e-3d27-11e6-978f-cc097d7990b7.png)
- Inhalt and Benutzer Buttons are relicts from the normal search pages I think, they don't need to be there. (But that' only on the admin user screen, so not very urgent)
- No need for the dashboard headline
- We don't need the search bar twice on the dashboard, so remove it from the header.
- Search Buttons are somehow misplaced, should be on one line.
- I still get redirected to the search page from time to time, instead of going to the contact page directly. Probably I missed some feature revert / cache clear / search index manipulation? 
- With the autocomplete, we don't need the search Button at all, or am I mistaken?

Contact Page 
![auswahl_010](https://cloud.githubusercontent.com/assets/389844/16412198/3a289c42-3d2b-11e6-9141-fb771777b9e4.png)
- I don't see the CRM header with logo, search box and Menu to the Dashboard, but only the normal adminimal header.

**Comment by darshi-shah** [comment]
Hi Rainer,

Code is pushed on hkcrm branch, Please take pull and revert "hk_crm" feature.

Thanks
Darshi
