### ISSUE TITLE
Wrapup of things to complete until 15h Berlin time

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#27]
Hi Darshi, 

so here's the remaining things to do until 18h30 Mumbai time: 

Obligatory
- all the crm views and pages and contacts mustn't be visible by anyone but logged in users with the agent role... I checked http://addweb.dev.herbert-kohlmeyer.de/crm-core/contact/11 and I can see all the blocks without being logged in... so please restrict to agent role!!!
- create redirect of agent role on login to /search
- provide agent central and logout menu item on crm menu (even without agent central functionality)
- get rid of empty images on contact form rows
- add padding to create contact and activity items to make it easier to select
- make search criteria block translatable
- make Address, Email, Phone, Job Title, Birthday etc. translatable
- make create activities items translatable
- no blue color on hover and no white-space: pre; on autocomplete result list in header

Nice to have now (if easy) / possibly later (if takes too much time)
- format live search results like Mitarbeiter contact type (with email and phone)
- get rid of contact picture on inquirer (unclaimed leads)
- get rid of country, if it is Germany. Show other countries though. (unclaimed leads)
- prepopulate participants fields with acting agent and selected contact (activity lightboxes)
- hide date field on email (activity lightboxes)
- change date format from 06/15/2016 to the German 15.06.2016 (activity lightboxes)
- style select boxes with select2 so they are nicer and fully readable (activity lightboxes)
- if I change some values in a contact, the changes are not reflected immediately on the contact page. That is very disorienting. 
- test and refine the fields that have to be there on certain activities and the activities behavior / rules (might better be its own issue)
- provide what you have as agent central page, to give the client a better idea of what's still coming next.

Hope that's doable, keep me posted where you're at tomorrow.

**Comment by darshi-shah** [comment]
Hi Rainer,

Obligatory changes are done and pushed on git.

From other changes listed, following are done : 
- format live search results like Mitarbeiter contact type (with email and phone)
  Done
- get rid of contact picture on inquirer (unclaimed leads)
  Done
- get rid of country, if it is Germany. Show other countries though. (unclaimed leads)
  We can hide country for all. Let me know please.
- prepopulate participants fields with acting agent and selected contact (activity lightboxes)
  To do 
- hide date field on email (activity lightboxes)
  Done
- change date format from 06/15/2016 to the German 15.06.2016 (activity lightboxes)
  Done
- style select boxes with select2 so they are nicer and fully readable (activity lightboxes)
  Done
- if I change some values in a contact, the changes are not reflected immediately on the contact page. That is very disorienting.
  Done, this was views caching issue.
- test and refine the fields that have to be there on certain activities and the activities behavior / rules (might better be its own issue)
  Need more details on this
- provide what you have as agent central page, to give the client a better idea of what's still coming next.
  As discussed, I will be uploading mockup by EOD

Thanks,
Darshi

**Comment by heliogabal** [comment]
No, don't worry about the country, you can leave it as is.
- prepopulate participants fields with acting agent and selected contact (activity lightboxes)
  To do 

that's the only thing that's still open from here, I'll open another issue for the activities fields. Can be closed otherwise.

**Comment by darshi-shah** [comment]
Hi Rainer, 

Activity participants field is created automatically when activity type is created and this field is locked. So we don't have pre-populate option in this.  

However, if we create new participants field, we can use pre-populate in this. Please let me know how to proceed here. 

Thanks
Darshi
