### ISSUE TITLE
Wrapup of things to complete until July 14th, 11h Berlin time

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#28]
I'll add to this list all the still missing parts and pieces I encounter to make the CRM functional.
- Date fields always have to have proper German format: 14.7.2016 14h32 (Create Contact forms, Create Activitiy forms, Contact birthday field etc.)
- ~~Font should be a consistent sans-serif throughout the CRM~~
- ~~Lightbox doesn't close on click on X, only when the overlay is clicked. If possible, make lightbox not fixed size, but expand bigger when there is more content.~~
- ~~Get rid of fields in CRM individual contact: field_crm_bemerkungen, filed_crm_ansprechpartner (if it is replaced by responsible agent field)~~
- Make company and connection autocomplete field with edit and add dialog capabilities.
- When I click on Create Contact -> Add Prospective buyer, sometimes two lightboxes open on top of each other ("Add Individuum" and "Kunde hinzufügen"). The select list content is cut in half sometimes: http://dl.dropbox.com/u/141872/Auswahl_017.png 
- ~~meeting and task icons in unclaimed leads table and my contacts table are missing~~

**Comment by darshi-shah** [comment]
~~we also need to remove  Anfrage and Kontaktformular from create activity on CRM pages.~~

**Comment by heliogabal** [comment]
~~Live Search Results seems to have a regression: Only Name is shown, phone number and email address have gone again.~~

**Comment by heliogabal** [comment]
~~Styling of Search Criteria is off: 
http://dl.dropbox.com/u/141872/Auswahl_018.png~~

**Comment by heliogabal** [comment]
~~I had to redo all permissions, recreate the search index, all facets, all block settings for search criteria. Can't this be saved in features? When I avtivate hk_crm feature, I get a note about missing permissions that are not set anywhere.~~

**Comment by heliogabal** [comment]
If I'm clicking on Agent Central as an agent, I don't get to /crm-core/agent-central/[agent-id] but only to /crm-core/agent-central

**Comment by heliogabal** [comment]
**Activities**
- ~~If I create an activity I'm redirected to the activity view and don't stay on the CRM page I have been on.~~
- ~~Activities are not filtered by agent. There should be a contextual filter on the crm core activity author probably.~~
- ~~If I add a new activity "task", I can't scroll down to the Save button~~

**Comment by heliogabal** [comment]
**Agent Calendar**
- ~~Activity dates in Agent Calendar are always 01 Jan~~
- ~~Activity time is always shown as 01:00 AM~~
- ~~Week, Month and Year views shows only 1 meeting, even if there are more (works now, so there seems to be a caching issue with the view)~~
  ~~\- Meetings in Calendar need edit links~~

**Comment by heliogabal** [comment]
**References**
- I still can't select a responsible agent. Select list is empty, even though there are agents.

**Comment by heliogabal** [comment]
~~Order of contact create fields:~~
- Name
- Individual Type 
- Responsible agent
- Secondary agent
- E-Mail
- Phone
- Address
- Other
- Job title
- Birthday
- Languages
- Company
- Connection

~~Right now, there are two company fields, the text field can be deleted.~~

Company and Connection fields don't work as expected. Is it impossible to use references dialog with these fields? Ideally, it should be possible to select/search an existing company/connection or create a new one directly in the form, like it is with object and apartment.

**Comment by heliogabal** [comment]
~~Please also tag all the views you created with addweb so it will be easier to find and decide which views are not needed any longer.~~

**Comment by heliogabal** [comment]
~~Some strings still have forbidden markup around to provide styling, so I can't translate them or they are not styled correctly. Example: 
`<h2 class="block-title">To-do Task</h2>`~~

**Comment by heliogabal** [comment]
**Participants field**
- The participants field is vital to make the decision what activity to show to what agent and contact.
- As the crm core participants field is a mandatory field, we will have to find a way to work with that. 
- Even if we create another field for participants, we would have to fill the crm core field with something. 
- The second field you created doesn't get prepopulated either, and I can only input one participant.
- The second field is weirdly styled so it is not obvious that this is a textfield.

**Comment by heliogabal** [comment]
~~**My Contacts view on agent central**
minor flaw that should be fixed last... when I have several contacts in the table, I only get the content of the last activity on the last one, the previous one only misplaces the row underneath.~~

**Comment by heliogabal** [comment]
~~One thing I found that is going to irritate the client immensely: on agent central, the destination on activity lightboxes is set to /search, so the agent goes back to the Dashboard instead of staying at agent central. I realize that it's now set in the views footer, so there can't be any logic involved, only tokens, but it would be very important to find a solution here.~~

--- This is fixed and pushed on git

**Comment by heliogabal** [comment]
I updated hk_crm feature with display suite for crm contact form (hide field_crm_bemerkungen) and added the crm relevant things that were removed from hk_admin. You can check the feature here: https://github.com/heliogabal/hk_crm.git

**Comment by heliogabal** [comment]
I updated both hk_adminimal and hk_theme with some finishing touches and UX improvements and pushed both to github.

**Comment by heliogabal** [comment]
~~The Add Individual double lightbox issue is still not fixed:
http://dl.dropbox.com/u/141872/Auswahl_020.png~~

~~It happens when I'm on the Dashboard and click on create prospective buyer. Is it possile the lightbox gets loaded once by javascript and once by php? This should be tackled first thing in the morning, and I would need a patch or some instruction how to fix that without another pull, as I can't risk to lose my translations or block positions or anything by doing a new pull before the demo.~~

--- this is fixed and pushed on git.

**Comment by heliogabal** [comment]
If I create a meeting from the unclaimed leads table, after saving I'm redirected to the normal activity-add form, and there are the following problems:

    Participants field is required.
    The value input for field Date is invalid:
    The value 07/20/2016 12:45 does not match the expected format.

Apart from the problems that prevent me from creating a meeting, it would be nice if there could be form validation insider the lightbox, to prevent being stuck somewhere without a menu.

**Comment by heliogabal** [comment]
- When I create any activity, it is not reflected in the activities table on the contact page, it seems only inquiry and contact form are shown. E-Mail, Phone call and meeting should be shown there as well.
- The last activity is also not reflected on the agent central my contacts table.

**Comment by heliogabal** [comment]
~~**My Contacts view on agent central**~~
~~\- I can't translate the last contact time like yesterday or Before. It seems to be very custom, I can't find this in the view...~~
~~\- the table should be sorted after the last contact time (newest contact on top)~~
~~\- it says "-0 days Before" instead of today~~

~~--- this has been fixed and pushed on git. You need to add translations and add them in hk_translate feature please.~~
