### ISSUE TITLE
Add phone icon with number to service menu

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#29]
We need an addition to the service menu: A telephone icon that reveals the main telephone number when hovered: 
![servicemenu_phone](https://cloud.githubusercontent.com/assets/389844/17290620/b443050c-57df-11e6-972d-c846624cf975.png)

![icon_telephone](https://cloud.githubusercontent.com/assets/389844/17290668/eee8a072-57df-11e6-822a-7d2dd65456d2.png)

**Comment by darshi-shah** [comment]
Hi Rainer, 

These changes are pushed on develop branch. Please take pull and revert hk_crm feature.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
maybe I didn't explain myself precisely enough... the phone icon padding was meant to be in the desktop view as well. If you compare the first screenshot with your work, you will realize that the icons are cramped together and don't have enough space between them to be nicely selectable:

![auswahl_027](https://cloud.githubusercontent.com/assets/389844/17365330/f51261f2-5985-11e6-8b35-ffde8ba26633.png)

so the icons in desktop view should have a padding to their left (maybe 0.5em?) to make the clickable surface bigger and give them some withespace.

Then, on Tablet view, the icons should be evenly distributed and far enough away from each other to be easily selected with a finger. This is what it looks like now to me:

![auswahl_028](https://cloud.githubusercontent.com/assets/389844/17365456/80cfba0a-5986-11e6-9034-40b81bd45b2f.png)

So there is not enough space between favorite and phone, and the language selector is too far away.

When I select the phone icon on iPad, the tooltip doesn't show correctly:

![auswahl_029](https://cloud.githubusercontent.com/assets/389844/17365490/b2afc376-5986-11e6-9bd9-a4e37f5acd77.png)

On iPhone, its better and the tooltip shows, but the language icon is still too far down:

![auswahl_030](https://cloud.githubusercontent.com/assets/389844/17365566/0f7e773c-5987-11e6-9aaf-7ca44d633786.png)

Hope that makes it more clear...
