### ISSUE TITLE
Clean up git repository structure

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#30]
There are some problems with the current repo when applied to the BOA Aegir environment. It would be easier if these could get fixed to avoid confusion and don't expose sensitive data to the world.
-  we can probably exclude sites/addweb.dev.herbert-kohlmeyer.de sites/herbert-kohlmeyer.de sites/hk-addweb-7431-prod.dot etc. from the git repository altogether. We shouldn't ever change anything in these folders anyway, and this creates unnecessary folders that get overwritten by the aegir migration, so we are always in a state of difference with unnecessary folders that is confusing. And there are environment specific config files with sensitive data in there.

Plus, the file site/*/modules/boa_site_control.ini must have this configuration to activate solr search properly:
[system_control]
solr_integration_module = search_api_solr
solr_update_config = NO
solr_custom_config = YES
;sql_conversion_mode = NO
;disable_user_register_protection = FALSE

this will get copied over by aegir, but is currently not correct on addweb.dev.herbert-kohlmeyer.de, so creates a diff as well. Based on this file, BOA activates the appropriate SOLR core every other morning, so if it is the wrong file, I need to wait a day before I can test with SOLR.
- I'm not sure if we also can get rid of sites.php in our repo, would have to be checked.
- Then, permissions should be set to: 644 instead of 755 for all files, as this is the permission that aegir changes everything to once a night, and you always get huge diff files with mostly permission changes out of it. If your local environment could be run with the same permissions as BOA, that would be beneficial.

These are the permissions on BOA:
[addweb_crm_stage]$ ls -la
total 324
drwxrwsr-x 12 o4507778742 users      4096 Aug  8 16:00 .
drwxrwsr-x 35 o4507778742 users      4096 Aug  5 15:46 ..
-rw-rw-r--  1 o4507778742 users       317 Jul 30 09:20 .editorconfig
drwxrwsr-x  8 o4507778742 users      4096 Aug 10 13:34 .git
-rw-rw-r--  1 o4507778742 users       304 Jul 20 12:18 .gitignore
-rw-rw-r--  1 o4507778742 users      9959 Jul 12 16:57 .htaccess
-rw-rw-r--  1 o4507778742 users    108616 Jul 30 09:20 CHANGELOG.txt
-rw-rw-r--  1 o4507778742 users      1481 Jul 12 16:57 COPYRIGHT.txt
-rw-rw-r--  1 o4507778742 users      1717 Jul 12 16:57 INSTALL.mysql.txt
-rw-rw-r--  1 o4507778742 users      1874 Jul 12 16:57 INSTALL.pgsql.txt
-rw-rw-r--  1 o4507778742 users      1298 Jul 12 16:57 INSTALL.sqlite.txt
-rw-rw-r--  1 o4507778742 users     17995 Jul 12 16:57 INSTALL.txt
-rw-rw-r--  1 o4507778742 users     18092 Jul 30 09:20 LICENSE.txt
-rw-rw-r--  1 o4507778742 users      8806 Jul 30 09:20 MAINTAINERS.txt
-rw-rw-r--  1 o4507778742 users        12 Jul 12 16:57 README.md
-rw-rw-r--  1 o4507778742 users      5382 Jul 12 16:57 README.txt
-rw-rw-r--  1 o4507778742 users     10123 Jul 12 16:57 UPGRADE.txt
-rw-rw-r--  1 o4507778742 users      6604 Jul 12 16:57 authorize.php
drwxrwsr-x  2 o4507778742 www-data   4096 Jul 13 20:11 cache
-rw-rw-r--  1 o4507778742 users       720 Jul 12 16:57 cron.php
drwxrwsr-x  4 o4507778742 users      4096 Jul 30 09:20 includes
-rw-rw-r--  1 o4507778742 users       529 Jul 12 16:57 index.php
-rw-rw-r--  1 o4507778742 users       703 Jul 12 16:57 install.php
-rw-rw-r--  1 o4507778742 users     10116 Jul 12 16:57 js.php
drwxrwsr-x  4 o4507778742 users      4096 Jul 30 09:20 misc
drwxrwsr-x 43 o4507778742 users      4096 Aug 10 13:34 modules
drwxrwsr-x  2 o4507778742 users      4096 Aug 10 13:34 patchs
drwxrwsr-x  6 o4507778742 users      4096 Aug 10 02:26 profiles
drwxrwsr-x  2 o4507778742 users      4096 Aug 10 13:34 scripts
drwxr-x--x  7 o4507778742 users      4096 Jul 14 09:48 sites
drwxrwsr-x  7 o4507778742 users      4096 Jul 12 16:57 themes
-rw-rw-r--  1 o4507778742 users     19986 Jul 12 16:57 update.php
-rw-rw-r--  1 o4507778742 users      2200 Jul 12 16:57 web.config

**Comment by darshi-shah** [comment]
Hi Rainer, 

sites/herbert-kohlmeyer.de sites/hk-addweb-7431-prod.dot etc and sites/addweb.dev.herbert-kohlmeyer.de ne  are added in gitingnore. 

SOLR configurations are also pushed on dev. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Thanks! I'll pull to see if everything works as expected.

**Comment by heliogabal** [comment]
Pulled and reverted features. 

I realized that I did a mistake adding addvag_cron_timestamp to the feature hk_base. If you could also get rid of that value, the feature won't show as overwritten all the time.

Then, I am getting the following error popping up concerning the fonts.com script since several days:

A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://fast.fonts.net/jsapi/69…3128-41dd-a024-e20f5106e17e.js:34

Therefore, I changed the fonts.com script tag in hk_theme and I also added the rewritten hk_adminimal custom.css so I don't always have to compass watch the theme after a pull. I pushed this to develop.

Also, I keep getting the domain value in the DB overwritten, I can't make out when this actually happens, but I had to change it twice now since the last pull. This is quite annoying and possibly dangerous, as you're getting redirected to the live site once that happens. So please have a look where this might be coming from and hopefully fix it.

**Comment by heliogabal** [comment]
I think the domain values change once you revert hk_search (or probably any feature). There is also the path for the solr core that should be excluded from the feature, as it is different on dev/stage/lice: Component type: search_api_server

Although I didn't revert hk_translations, it got somehow applied I think, as the domain value is set there in Component type: language

This should probably just be left empty in the feature, as it will be different for the sites as well.

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are done and pushed on develop branch. Please check.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Regarding file permissions,

yes its ideal to provide 0644 to all files, but however we experience that after giving this permission to files, feature stopped working, and it may be due to the fact that server user is not the owner of the files, in case of apache its www-data.

So can you please confirm it for us, or you want us to change it irrespective of that.

Thanks

**Comment by heliogabal** [comment]
Well, if they are not 0644, omega8 BOA will change them to 0644 every night, so I always get this huge git diff although nothing changed (see attached).
[permissions.txt](https://github.com/saurabhd/hk_realestate/files/480678/permissions.txt)

This makes it really hard to actually see what changed... so at least these files could have their permission changed from my point of view. 

The omega8 user/permission structure is quite elaborate, but very secure, and I can't change anything on it.
There is the o4507778742.ftp user (me), and the o4507778742 (omega8) that are in the users group and the webserver (www-data:www-data). Somehow they manage that it is working fine. Maybe you can adapt your settings to match that of the server, but only it it doesn't take too much time.

Otherwise I can live with the nuisance to not see what actually changed or scroll myself to death ;-)

**Comment by heliogabal** [comment]
I this a lot of work to change on your end? If so, I would check and close this issue.
