### ISSUE TITLE
Devlop merged to master

### ISSUE THREAD

**Issue by darshi-shah** [saurabhd/hk_realestate#32]
Hi Rainer,

Develop branch is merged to master branch. 
Please note that this do not have your last commit in it.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,

Ok, thanks for that. No problem with my latest commit, it's only slightly more work each time to change these small things by hand, so we can push them next time around.

**Comment by heliogabal** [comment]
Some things I noted:
- When I send an inquiry from the map popup, I once again get redirected to the inquiry form, where I can see the inquiry for field. I forgot what I need to do to fix that... please remind me! Also, I only inquired for one apartment (nid 3519), but there were two others in the list (3609 and 3705):
  ![selection_018](https://cloud.githubusercontent.com/assets/389844/18062022/53d83e1a-6e25-11e6-9608-01e72023ffc2.png)
- I still can't translate the strings from the map pop, as they contain disallowed HTML:
  [field_object_images]  <p>[field_object_ref_field_object_txt_map_popup_value]</p> <p>[field_obj_apartments] apartments in total</p> <div class="wo"><i class="icon-hk-icon-location"></i>[field_object_ref_field_address_thoroughfare] [field_bezirk]</div> <div class="tablehead"><span class="id">Object ID</span><span class="rooms">Rooms</span><span class="space">Space (ca.)</span><span class="price">Price</span><span class="more">&nbsp;</span></div>  
- you said that #8 would be fixed, but I still can see the facets on page load on the static pages, the toggle is not inverted. Shouldn't this be also pushed to master?

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are pushed in develop branch. I will merge these once you confirm. Please make sure to revert hk_search feature.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

Messages are shown on map upon inquiry submission. This is pushed in develop branch. Let me know if I can merge this in master.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
Messages show fine now and the form gets successfully sent. Search facets only show on static pages after clicking the search icon. Translations I will have to check on live, as somehow I could translate them on dev. So good to go to merge with master again...

Only one bug left I found: When sending the form for shadow apartment, the email to office gets sent with the correct apartment filled in. But when I send a normal apartment inquiry, the apartment isn't filled in, so the agent doesn't know which apartment is concerned.

**Comment by darshi-shah** [comment]
Hi Rainer,

This has been fixed. Please revert hk_search. 

Thanks,
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
thanks! Awesome, that means you can push to master now. I tested and everything seems to be ok.

best,
Rainer

**Comment by darshi-shah** [comment]
Hi Rainer, 

The develop branch is merged in master. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
thanks, I tested and pushed to the live site, so inquiries are working better now. But I happen to realize that the email to the client after successful inquiry doesn't get sent any longer. 

It might have to do with the value in the rule rules_e_mail_to_client_and_office_when_inquiry_sent:
recipient is set to crm-core-activity:field-activity-participants:1:primary-email 

but maybe the order of the recipients changed or there is no participant:1 any longer, only participant:0? 

I remember I had to set one participant to ilka, don't know if that is the case any longer. Could you please check that?

Thanks!

**Comment by heliogabal** [comment]
The participants field is also posing the same problem. In https://herbert-kohlmeyer.de/admin/structure/views/view/crm_anfragen/edit/page I managed to solve it by setting multiple field settings to: 
show 1 value beginning with 0 in reversed order

something like that should also be done with the unclaimed leads table. Could you do that for me please? Thanks!

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are done and pushed in develop branch. Please check. You will need to revert hk_crm feature.

Thanks
Darshi
