### ISSUE TITLE
CRM: Get rid of unnecessary search messages on dashboard

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#34]
I'm seeing the block title and a "search doesn't give any results"-message on the CRM dashboard.

There's no need for these, so please see how we can get rid of them. Also, I was wondering if this might be the case because we are on an actual search page, but could as well define another URL for the dashboard to live on that won't show these. Then, we could also only have one theme for the CRM and wouldn't have to have this sketchy thing where the dashboard is actually in hk_theme and the rest in hk_adminimal_theme.

That's confusing and will lead to problems in the future. So maybe check if you can solve both problems at a time without too much effort. 
Thanks!
![crm_search](https://cloud.githubusercontent.com/assets/389844/18642714/0a327fc2-7ea2-11e6-89d9-27c97997e374.png)

**Comment by darshi-shah** [comment]
Hi Rainer, 

We can make CRM use hk_theme instead of hk_admininal_theme. That would mean that we will have to bring all changes we did in hk_adminimal_theme to hk_theme. We will need to adjust blocks, tpls, search facets etc along with CSS. We can start with this after upgrades are done.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
please hold off from changing theme until further nitice, but if you could hide the search message and the title, that would help.

**Comment by darshi-shah** [comment]
Hi Rainer, 

Search messages and title are done. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Great, that was quick! I'll be checking tomorrow, and put this on hold then for the theme change question.

**Comment by heliogabal** [comment]
Ok, I checked and the changes are good to go to master. For the theme, we should probably do a separate sub-project to refactor and clean up the whole theme one day. For now, closing this.
