### ISSUE TITLE
Update Modules

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#35]
Hi Darshi, 
I just saw there are security updates for admin_views and flag modules, and those other updates have updates as well: ctools, cdn, crm_core_profile, entity, entityreference, entityreference_feeds, uuid. I also installed feeds_tamper_string2id and had to use the dev version of feeds_tamper to do the import of 120 apartments. So if you could update and add those as well to dev for testing, that would be great.

**Comment by darshi-shah** [comment]
Hi Rainer, 

I installed hacked module to be sure that we do not miss any patch we applied to modules.  

I have upgraded administration views, block cache alter, flag(with patch), WYSIWYG.
blockcache_alter module was present on site but not added in git so I have added it. 

These upgrades are pushed on develop branch. I will be upgrading more modules tomorrow.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

All modules are upgraded. Here is list of all modules with patch: 

1 - administration views
2 - block cache alter
3 - ctools - done, patch is in new version (need to run drush rr to solve Fatal error: Class 'ctools_export_ui' not found)
4 - entity api , patch in following files :
includes/entity.controller.inc
includes/entity.wrapper.inc
views/entity.views.inc
views/handlers/entity_views_field_handler_helper.inc
5 - entity reference
6 - flag - done, patch
7 - uuid 
8 - uuid features integration
9 - wysiwyg
10 - crm core profile

I have checked local site after each upgrade. CRM and shadow is working fine. Please take pull on dev so we can go through final testing tomorrow for this.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
great, seems fine by me. When I was looking at the hacked modules, I was a bit surprised to see some that I didn't know where hacked: 
date
entity_rules
i18n
adminimal_admin_menu
adminimal_theme

Did you hack these? For adminimal_theme, I would prefer to have these changes in hk_adminimal - that's why I created the subtheme, so the theme can be updated without a hassle. 

Apart from that, I think I can close this.

**Comment by darshi-shah** [comment]
Hi Rainer,

Here is list of patches against these modules : 

1 - date  - https://www.drupal.org/files/issues/week-pager-next-prev-year-fix-1874422-23.patch
This was to solve agent calendar next prev button issue.

2 - entity_rules
This was part of initial commit. We haven't made any changes in this.

3 - i18n and adminimal_admin_menu
These patches were listed in make file. Please refer : https://github.com/heliogabal/hk2/blob/master/drupal-org.make

4 - adminimal_theme
We made this change. We have now removed this and pushed in develop branch.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
ok, so now I know what is going on. Gonna check on develop, then I can close this.
