### ISSUE TITLE
Image restrictions

### ISSUE THREAD

**Issue by darshi-shah** [saurabhd/hk_realestate#36]
We realized that there are minimal image sizes defined in the field definitions of     field_object_images (in the object) and field_apart_pictures, field_apart_gallery in apartment. I already changed those because I thought they were in the database, but the values got reset somehow. There shouldn't be any restrictions. Can you have a look if you don't have anything else to do where this is and change it (probably hk_content_type feature), so we don't run into this problem again?

**Comment by darshi-shah** [comment]
Hi Rainer,

removed min image size restriction from field_object_images and field_apart_pictures, field_apart_gallery. You need to revert hk_ct featute.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
unfortunately, I realized I jumped to short to solve that problem. I had this weird bug when saving apartments, there were errors about missing images that couldn't be copied, so I had to change the filefield_path settings for location and naming of these file_fields: field_object_images, field_apart_pictures and field_apart_gallery. See the screenshots attached on the exact settings I would need incorported in the feature. 
field_object_images:
![file_setting_field_object_images](https://cloud.githubusercontent.com/assets/389844/18955357/5b61da34-8657-11e6-9873-4b97ee205db1.png)

field_apart_pictures:
![file_settings_field_apart_pictures](https://cloud.githubusercontent.com/assets/389844/18955447/d1515e04-8657-11e6-9a9a-5417b46cae79.png)

field_apart_gallery:
![file_settings_field_apart_gallery](https://cloud.githubusercontent.com/assets/389844/18955372/70b73d02-8657-11e6-88cf-6ff30fc29210.png)

Please change those and update the develop branch so I can check if that is all there is to fix the problem finally. This has a high priority as it affects the clients work with the site directly, so should go in a separate hotfix push to master as soon as it has been tested.

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are pushed on develop branch. Please revert hk_ct feature.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
thanks for the fast work. Closing this, as it is incorporated in master.
