### ISSUE TITLE
changes to repo, module addition and deletion

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#38]
Hi Darshi, 
I installed feeds_tamper_string2id and translation_table to the live site directly. Please add those to the develop branch as well so we can incorporate those modules in the future master branch. 

I also realized that we don't need mandrill module any more in the repo (they discontinued their free tier, so I deactivated the modules a while ago), so you can delete it from the modules folder to clean up a bit.

Thanks!

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are pushed in develop.

Thanks
Darshi

**Comment by heliogabal** [comment]
Thanks! Closing this.
