### ISSUE TITLE
Get rid of Schattenwohnung workflow state

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#40]
As we almost finished the shadow apartments, we don't rely on a special workflow state "Schattenwohnung" any more but only on the select field. So the workflow state is useless now and can be removed completely.

That will further simplify the node edit form, which will make the client happy ;-)

**Comment by darshi-shah** [comment]
Hi Rainer,

We removed the "Schattenwohnung" state but we can not incorporate changes in features. Please follow below steps : 

1 - enable Workflow UI and Workflow Clean Up modules.

2 - goto admin/config/workflow/workflow/manage/draft_ready_published_archived/states and make "Schattenwohnung" inactive. You will see count next to each state which shows number of content in this state.

3 -  goto admin/config/workflow/workflow/cleanup and select and delete inactive state.

4 - clear cache.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
ok, thanks for testing it out. I forgot that the workflow field can't be saved in a feature, but I also realized that we have to manage to transfer the Schattenwohnung state to another one first, and we need to clear the editorial process for that beforehand. As long as there is still the multiplication of shadow apartments on the map, it might also not be a good idea to publish the 50 apartments all at once... so putting this on hold until I can manage to change it.
