### ISSUE TITLE
Translation of Mr. and Mrs. in CRM core / name module

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#41]
Here's a tricky one: 
The CRM Core contact module uses the name field module to store the whole name including title, credentials etc. 

Although the title (Mr., Mrs.) are translated (Herr, Frau), and in the CRM Core profile I get the translated value to select in the dropdown, in lots of other places (for example the tokens in the E-Mail that is sent after inquiry from is sent, or the search box in the CRM search), these translations are not used. 

It seems to be related to some tricky and long standing issues from the name module (https://www.drupal.org/node/1788156, even for Drupal 8: https://www.drupal.org/node/2715265)

I tried using taxonomy terms for the title, even installed the values module to find a working solution to this (which for now does nothing). Please have a fresh look at that and let me know if yo need more details.

**Comment by darshi-shah** [comment]
This is done and pushed in develop branch.
