### ISSUE TITLE
CSS glitches

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#42]
There are several minor CSS glitches that got introduced somewhere along the way that should be corrected:
~~On the apartment page, the green check is positioned too low:
.ausstattung ul li {
    background-position: -10px -46px !important;
}
there are other instances of this that get overwritten, so please remove the !important and position the li with -10px 53px;~~

~~the footer on the map is only reachable once you scroll down. It used to sit exactly on the bottom of the window. There shouldn't be any scrollbar. On mobile landscape on the other hand, the footer is sitting too high. On mobile portrait, the scale (which has a bigger font as before) and mapbox attribution sit under the footer instead of just on top of it.~~

~~the search box on mobile is too wide (80%), so the close icon shows under the side icons. Both Icons need to be comfortably clickable by touch. This is still the case on my Motorola G3...~~
![search_close_mobile](https://cloud.githubusercontent.com/assets/389844/19050217/f2b86b88-89ad-11e6-926b-160b4a37a8b5.png)

~~by adding the select checkboxes to the map popup, the tablehead doesn't align with the corresponding values any longer:~~
![tableheader](https://cloud.githubusercontent.com/assets/389844/19050078/4d492fde-89ad-11e6-8f7d-e12db148170b.png)
![tableheader_normal](https://cloud.githubusercontent.com/assets/389844/19050081/50da23c4-89ad-11e6-8fa2-d4517bc8cf7c.png)
![tablehead_mobile](https://cloud.githubusercontent.com/assets/389844/19050156/a7ca544c-89ad-11e6-8730-8233bcc1a256.png)

This is better now, but the table is still too wide and there is unnecessary whitespace between the tds. Can we find a bulletproof way of making the tds only as wide as needed for either their tr or content?

**Comment by darshi-shah** [comment]
Hi Rainer,

This is pushed in develop branch.

Thanks
Darshi

**Comment by heliogabal** [comment]
this is not fully resolved, please review the remaining issues.

**Comment by darshi-shah** [comment]
Hi Rainer,

Alignment issues are pushed on develop branch. Please take pull. 

As for search box on mobile devices, can we show close button at bottom right instead of decreasing popup width ? Please let me know.

Also for table column space, we have fixed table width for responsive and table column width increases if we have less columns.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
ok, I'll check. 

That would be inconsistent with all other occurrences of the lightbox, so makes bad UX. What is the problem with just making it a little less wide? Say 75% instead of 80%?

Table header: Space (.ca) lost it's translation again, and in the normal apartments, there are two table headers now:

![double_table_header](https://cloud.githubusercontent.com/assets/389844/19599937/13dd648c-97a3-11e6-888c-bae179bfd8d0.png)

**Comment by darshi-shah** [comment]
Hi Rainer,

I have made changes for popup size. I need to test it on dev to make sure it works well. Please take pull.

As for translation, I refreshed strings and translation is working fine. Please check on dev site. 

Also, I do not see two table headers on dev site or test site. Can you please let me know if this is still an issue.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
pulled, reverted and caches cleared. Search Box size is better now, could you still position it so that the left border of the search aligns with the right border of the zoom icons (+ and -). Would look cleaner that way. 

the double headers seem to be gone now for me as well.

**Comment by darshi-shah** [comment]
Hi Rainer,

Alignment issue is pushed on dev, please take pull. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Cool, now it's falling in nicely ;-)
