### ISSUE TITLE
Computed field: allocable + not allocable incidental cost = incidental cost

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#43]
We already have two fields field_apart_alloc_incident_costs and field_apart_nalloc_incid_cost that should be combined in a third field (sum of both fields) incidental_cost that should be visible in the apartment details.

**Comment by darshi-shah** [comment]
Hi Rainer,

This is done and pushed in develop branch. Please revert hk_ct feature.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
looks almost ready. Just rename the label to Incidental Cost instead of Apartment Incidental Cost, and hide the field if it is empty (no 0 €/month). Then it is good to go.

**Comment by darshi-shah** [comment]
Hi Rainer,

This is done and pushed on develop branch. Should we also hide  Allocable incidental costs and Not allocable incidental costs fields as well if they have 0 value ?

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
I thought they were already hidden when empty, but I was wrong. Yes, also hide those if they're empty.

**Comment by darshi-shah** [comment]
Hi Rainer,

Allocable incidental costs and Not allocable incidental costs both allows negative values. Should we show them? 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 

No, there can't be negative values in these fields, so just show the ones >0. Must have been an oversight when creating these fields.

Thanks,
Rainer

**Comment by darshi-shah** [comment]
Hi Rainer,

These changes are pushed on develop.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
I thought they were already hidden when empty, but I was wrong. Yes, also hide those if they're empty.
