### ISSUE TITLE
ng-lightbox on map doesn't work any more

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#44]
Hi Darshi, 
the Anfrage button on the map doesn't work any more - on the live site and on dev. Instead, the full form is shown in it's own page - revealing the shadow apartment title and node id. That's highly critical and should be fixed asap. What's more, even if I select only one apartment from several, the whole list is sent as inquiry for, so the agent won't know which apartment was inquired actually. 

I tested if this is a problem with advagg, but even without aggregation, this is happening.

please fix this and push it to master when done, so I can pull somewhere on the road.

**Comment by heliogabal** [comment]
there's also something strange about the clustering of markers on the live map. On the highest zoom level, markers overlap instead of clustering. If you could have a look at the differences between live and dev and adjust accordingly, that would be great. On the map load zoom level, they should be unclustered as on the live site, but zooming out, they should cluster together and don't overlap. 

Thanks!

**Comment by darshi-shah** [comment]
Hi Rainer,

ng-lightbox issues are fixed and pushed in master. Please check.

The clustering issue was with configuration and hk_search feature not being reverted. I have reverted this as well and map works fine now.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi,
Thanks. I just changed the js on live for now, as I don't want to risk a whole pull on prod while I'm busy. Will do that tomorrow. 

Best wishes from Dublin!
Rainer

**Comment by heliogabal** [comment]
Hi Darshi, 
I created a new master pull and copied the prod site over, and the ng lightbox form is working, but there are other strange problems that also appear on the prod site. Don't know if they're connected, that's why I mention them here... the Details links to the apartment pages from the lightbox don't work reliably. I can open them in a new tab, but nothing happens when I just click them. Sometimes, instead of going to the apartment page, the form is opened. Seems to be some problem with the js still.

**Comment by darshi-shah** [comment]
Hi Rainer,

The code for this was pushed on master but when I check http://herbert-kohlmeyer.com/ the code is missing there. It has old code only. 

On http://up.dev.herbert-kohlmeyer.de, on details click page redirection happens. WSOD can be .htaccess issue. Can you please check if the file exists? If its still an issue, can you please create a login for me so I can login and check ?

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
strange, I changed the code in script.js manually from the git diff. up.dev. should have your addweb user as in prod. There is no .htaccess as the webserver is nginx, so it is all managed by omega8.

**Comment by darshi-shah** [comment]
Hi Rainer,

The code was added here : https://github.com/saurabhd/hk_realestate/commit/c4e48b2bc8517d928e77e9b9f47aaae3f20edfcc

Please see diff for script.js

I am checking for WSOD.

Thanks
Darshi

**Comment by heliogabal** [comment]
I know, I changed the jQuery triggers accordingly. Didn't change anything else, as it seemed it was not related to the lightbox issue.

**Comment by darshi-shah** [comment]
Hi Rainer,

https://herbert-kohlmeyer.com/sites/all/themes/hk_theme/js/script.js please search 
`jQuery(".leaflet-popup-pane").on('click', function(e) {`

Replace it with 
`jQuery(".leaflet-popup-pane").on('click','.inquiry-button .home-page-popup-inquiry', function(e) {`

Thanks
Darshi

**Comment by heliogabal** [comment]
alright, that was it...

**Comment by darshi-shah** [comment]
Hi Rainer, 

for WSOD, please check error here: http://up.dev.herbert-kohlmeyer.de/die40/2-zimmer-1-og-mitte
I added custom block on this site to show errors.

Same happens on contact page as well. This is working fine on dev and live site both. I will be debugging this tomorrow. 

Thanks
Darshi

**Comment by heliogabal** [comment]
ok. seems like it should be already fixed by the patch that was applied from here:
https://www.drupal.org/node/2112755

I'll try a new copy from prod to make sure I didn't miss anything crucial for tomorrow. Maybe that will fix things.
