### ISSUE TITLE
Dev deployment process

### ISSUE THREAD

**Issue by darshi-shah** [saurabhd/hk_realestate#45]
Process that we need to follow to deploy changes on dev site.

**Comment by heliogabal** [comment]
Right now, the process consist in:
- Push changes to develop branch
- Changes get pulled automatically into addweb_crm_stage platform
- Aegir control panel:
  - verify platform
  - verify addweb.dev.herbert-kohlmeyer.de site
- SSH
  - in ~/static/addweb_crm_stage/sites/all/themes/hk_theme: compass compile --force
  - in ~/static/addweb_crm_stage/sites/addweb.dev.herbert-kohlmeyer.de: drush -y fra 
  - drush cc all
