### ISSUE TITLE
Blank space in template.php prevents sitemap.xml to load

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#46]
Hi Darshi,
I couldn't open the sitemap.xml file on the live site, because there was a space before the opening <php tag in the template.php of hk_theme.

Once I removed the space, all is good. Could you check that this won't pop up again when things get pushed to master? Not sure where this comes from, as on dev all is good.

Thanks.

**Comment by darshi-shah** [comment]
I made this change and pushed in develop.
