### ISSUE TITLE
New Frontpage design estimate

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#51]
We agreed with Ashish that the existing map frontpage is not perfect for SEO. Therefore, the client wants to change the frontpage to a perfect landing page, with the map search only as an alternative supplementary method to find apartments.

We need a proposal for the perfect landing page structure with an estimate on how much and how long it will take to implement. The new frontpage should take into consideration that there might be some offers not in Berlin, that we can't show with our current map design. 

We have access to a lot of good photos of the offerings as well as surrounding cityscape, and there is the possibility to take custom photos if there is conceptual need for that.

The result should be a modern, responsive, graphically pleasing seo-optimized landing-page. Necessary texts can be provided.

**Comment by heliogabal** [comment]
These are the things I can think of for now that would need to be possible contrasting the existing frontpage: 
- unique value proposition to immediately tell the visitor what it's about and why it's for her
- better targeting of buyers as well as sellers, with direct CTA for sellers to offer their property to H+K
- possibility to promote special objects outside of Berlin (2 or 3 at a time)

**Comment by neeraj-addweb** [comment]
1: Home page with hover effect on menu link

 ![hk](https://cloud.githubusercontent.com/assets/18288247/20523667/284d1ae6-b0dc-11e6-9493-73a91491f230.jpg)

2: Home page with Search box option(Expand)

![hk_expand](https://cloud.githubusercontent.com/assets/18288247/20523720/63d37d62-b0dc-11e6-95c4-9f1c43acbfa1.jpg)

**Comment by Ashish-addweb** [comment]
PFA the revised home page mockups as discussed and let me know your views. Thanks

![3 1](https://cloud.githubusercontent.com/assets/8208518/20598661/1a201b68-b270-11e6-95af-5f1effccf806.jpg)
![1 2](https://cloud.githubusercontent.com/assets/8208518/20598662/1a4c159c-b270-11e6-9b75-b4c225b38d0f.jpg)
![Uploading 2 (2).jpg…]()

**Comment by Ashish-addweb** [comment]
PFA the footer bar with the desired options

![2 3](https://cloud.githubusercontent.com/assets/8208518/20640574/bb79c2b4-b407-11e6-83ff-99c27f3f0807.jpg)
![1 3](https://cloud.githubusercontent.com/assets/8208518/20640575/bba3f34a-b407-11e6-9d29-50469df6d41c.jpg)


@

**Comment by Ashish-addweb** [comment]
@heliogabal pfa the updated home page mockup with 'refer & earn' section in 3 different formats.
![pasted image at 2016_12_05 04_19 pm](https://cloud.githubusercontent.com/assets/8208518/20882471/1cac60c2-bb07-11e6-9e05-a892c40b72f0.png)
