### ISSUE TITLE
New project landing page for K55

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#52]
There is an urgent need for a separate landing page (or even several landing pages catering for different target groups) for the Project K55 with about 120 apartments. There is already the page of the project vendor, we should have additional buyer information including prices and CTA to contact H+K on top of the information provided there: www.k55-berlin.de

 Ideally, this could consist of: 
- keyword-optimized texts for target groups
- visually pleasing, modern touch
- separate domain or sub-domain if that is beneficial for SEO
- completely decoupled from the H+K site if that is beneficial for SEO
- optimal filtering of apartments that are mostly the same (apart from floor), but there are 6 different types
- possible to create likewise project-landing-pages in the future

This could maybe also serve as the blueprint for the new frontpage design, so we can have synergies there. 

As the financial benefits that can be granted to buyers will run out by the end of the year, it should go up asap.

But as before, we would also need an estimate before we can start with implementation.

**Comment by heliogabal** [comment]
Here is the wip wireframe for the Landing page: https://app.moqups.com/rhalbmann@googlemail.com/2oEvPoM62q/view/page/acf37230b 

Possible extensions include:
- language selector 
- apartment type block with floorplans
- inquiry form block
- inquiry button for selected apartments

There are still some strategical and technical things to figure out, but we should keep in mind that this should lead to a repeatable landing page creator in the end. There are plans on the way to do different landing pages in this manner for different borroughs, target groups etc., so more pages are going to come.

**Comment by darshi-shah** [comment]
Hi Rainer,

I have basic stuff ready with sub domain and  apartment list based on object ID. Please let me know when we can discuss about how to deploy this on dev. I will create features based on our discussion.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer, 

I have pushed changes for object changes on develop branch. Please take pull and evert hk_ct and hk_search features. Let me know what other elements needs to be added. For now, I have added only text, let me know how read more buttons will work. I will be working on basic theming part now.

Also, please let me know if we are keeping same header and footer as HK main site or will change them as per mockup. 

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

I have added a new theme(HK Subdomain) for sub domain as discussed on skype.  Basic design for new theme is already in place. Please take pull and let me know so I can make domain related changes.

I have also added some changes related to advantages tabs. To continue, please let me know following things: 

1 - Header on subdomain to remain same as main site or will it be like mockup ?
2 - Footer will not be fixed on sub domain. Please confirm this.
3 - Should we replace logo in footer with link as per mockup ?
4 - Object content type has different text field. Let me know which one to use for showing text above map.

I will be checking for apartment links tomorrow.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
1. yes, header like in mockup
2. yes, no fixed footer, this was only necessary on frontpage
3. No, good idea to keep the logo linking to the main page as logo
4. field_object_location is the right one

thanks!

**Comment by darshi-shah** [comment]
Hi Rainer, 

I have pushed theming changes on develop branch. Please take pull. hk_ct and hk_search needs to be reverted. 

Please check header on apartment page on subdomain. Let me know if any change is required in it.

I will be working on "Make appointment" button. I am checking if we can use existing inquiry form for this purpose. That way it will be part of CRM as well. I will keep you posted on this. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
probably we would have to go with a more traditional header whit the logo at the same spot as on the main theme because we can't know what images there will be in the future. We would probably also need a rudimentary menu so you can go back from the apartment pages to the landing page. Let me discuss that with the client.

If the inquiry button doesn't work because you don't have an apartment to inquire for, please also check if it would be possible to use the contact form and add the url to the landing page so the agents know which project they are talking about.

Thanks.

**Comment by darshi-shah** [comment]
Hi Rainer,

I have pushed theming changes and changes for make an appointment on develop branch. Please take pull. hk_ct, hk_crm and hk_search needs to be reverted.

For make an appointment, I am using existing inquiry form only. This form will now support both Apartments and objects. I have checked unclaimed leads table and object shows there. I will check emails on monday and make necessary changes.

Please let me know about menu and header. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, after checking some more, there are still these things to fix / consider:
- Get rid of the breadcrumb on the search
- The read more link doesn't work reliably all the time, somethimes it just reloads the whole page without opening
- Keep the selected value in the select dropdowns visible so people know what they are seeing results for
- Make sure rooms are found, right now, there are "no matches"
- Double-check that the inquiry for the object lands in the inquiry table in the CRM
- Make sure that there are only k55 apartments published under the k55 sub-domain
- Keep in mind that as soon as we promote the sub-domain, we would have to make sure the k55 apartments are only indexed once under the sub-domain and not a second time on the main page.

**Comment by darshi-shah** [comment]
Hi Rainer,

Get rid of the breadcrumb on the search
- This is done. Please take pull on dev site.

The read more link doesn't work reliably all the time, somethimes it just reloads the whole page without opening
- This works immediately after clearing cache. After subsequent page loads,  read more do not work and there are no errors in log and console. I will let you know if I find cause of this.

Double-check that the inquiry for the object lands in the inquiry table in the CRM
- Done

Make sure that there are only k55 apartments published under the k55 sub-domain
- Done

Keep in mind that as soon as we promote the sub-domain, we would have to make sure the k55 apartments are only indexed once under the sub-domain and not a second time on the main page.
- Index for k55 and main site is same. So we will add a new filter in main site views to exclude K55 object. Let me know if this approach is fine. 

In facet filters, I found couple of other issues, These are present on live site as well and are not related to K55. 

- On map page, filter count do not match with data on map. 
- Selected value is not displayed correctly.
- Facets do not show all values in drop down even if we have properties matching it.

We checked this with disabling select2 on filters and this is not related to it. I have also re-indexed the content but this hasn't helped.  We have upgraded modules sometime back. I will check if the issue has anything to do with this. I will let you know how it goes.

Thanks

**Comment by darshi-shah** [comment]
Hi Rainer,

The issue with search filters is with "Search API ranges" module. We  upgraded this module sometime back (Refer to #55). 

The module version was 7.x-1.4+dev-1.15 which worked fine. We upgraded it to 7.x-1.5. This version has many changes which seem to have caused this issue. I also checked with dev version and issue is there in this version as well. I have downgraded the module on dev site. Please take pull and let me know.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, thanks for finding this. Damn, upgrading to a stable version is supposed to make things more stable, not break them! I'll pull and check someday tomorrow, so you know after the holiday.

**Comment by darshi-shah** [comment]
Hi Rainer,

Keep the selected value in the select dropdowns visible so people know what they are seeing results for
- This is done for all facets except floor facet on k55 page. Floor is select list and rest are ranges. In ranges, selected value will be displayed. For select list, selected value is removed from drop down.

Keep in mind that as soon as we promote the sub-domain, we would have to make sure the k55 apartments are only indexed once under the sub-domain and not a second time on the main page.
- Index for k55 and main site is same. So we will add a new filter in main site views to exclude K55 object. Let me know if this approach is fine.

Thanks

**Comment by heliogabal** [comment]
Hi Darsi, 

> For select list, selected value is removed from drop down.

that's unfortunate, as this seems like a bug from a UX perspective. Users don't mind the type of field, they want to have a consistent behavior. If I select something, I want to see what I have selected.

> Index for k55 and main site is same. So we will add a new filter in main site views to exclude K55 object. Let me know if this approach is fine.

I think that was a misunderstanding. You're talking about the search index, I'm talkin about the Google index. For search it is fine and the K55 should be found on the normal page as well. But that leads to duplicate content, because K55 apartments now have two URLs (https://herbert-kohlmeyer.de/node/4122 and https://k55.herbert-kohlmeyer.de/node/4122). So we have to make sure that Google indexes only one version.

**Comment by darshi-shah** [comment]
Hi Rainer,

I am adding 2 issues that we discussed on skype here as well. 

1 - on k55 homepage, read more is not translated
2 - Footer  is not same as k55 home page for inner pages.

To fix floor, we would need to change the type of facet. Let me know if we can use ranges here as well.

I understood about sitemap. 

I would need a day or two to fix all these. 

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
unfortunately, we would need to fix this to be able to use the k55 landing page until we have finished the redesign. So 1) and 2) would need to be addressed, we can leave out the floor facet issue for now.

Hopefully, this can be done in 8h, as we're reaching the proposal limit here... Lutz wants to write the copy over the weekend, so it would be good to finish this until Monday.

**Comment by darshi-shah** [comment]
Hi Rainer,

1 - You can add translations for read more and read less by searching 

> div class="readmore-summary"

2 - In footer we are showing object text, so if we are not on object page, this block do not show.
![footer-object-text](https://cloud.githubusercontent.com/assets/15724372/24799692/3f366106-1bba-11e7-8eb0-948df5169124.png)

Other footer changes are pushed on dev. 

Please check and let me know.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
1 - ok, could translate that now.
2 - it's ok that the block doesn't show, but we need to prevent the social media buttons to take up all width and being outside of the footer. Has to be some CSS problem. Looks broken just now:
![k55_footer](https://cloud.githubusercontent.com/assets/389844/24848642/fccf43cc-1dc7-11e7-8f43-1d95a1080289.png)

**Comment by darshi-shah** [comment]
Hi Rainer, 

I fixed CSS for social media and pushed on develop branch. Do we need to take pull for this or webhook is in place ?

Thanks

**Comment by heliogabal** [comment]
I'll set up automatic pull for dev as well.
