### ISSUE TITLE
Remaining tasks to stabilization

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#53]
- Some markers are not clickable on map, popup doesn't open (for example the 12 apartments on Spenerstr. in Moabit or K55 with 21 in Mitte). It seems this is only the case when there are many apartments in the object. There might be some left over js code in hk_theme script.js or in the hk_leaflet modules script responsible for that.

**Comment by darshi-shah** [comment]
Hi Rainer,

I checked mentioned js and it seem to be in order. When we have more data, leaflet-popup-pane div remains blank for mobile. It seems that data is gathered for a sec but is not retained. 

Can we add show more/less functionality on dev and check this?

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

Restricting text input do not solve issue in every case. So as an alternative, we can use views_mobile module and hide data above table only in mobile. I have checked this in local and it works well for all cases. Do let me know if we can proceed with this and push this in develop branch. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, I don't like where this is heading... this used to work without a problem before, and there is no logical reason why this shouldn't work for objects with a certain number of apartments now. To find a workaround that would also add additional value to the site is one thing, to just try to patch it up with yet another module that is only used for this bug without understanding what is going on is not a good idea that is going to bite us sooner or later. I'm afraid we should rather get to the bottom of this. But can you push this to dev so I can have a look, and if I don't approve of the solution, we can remove it again?

**Comment by darshi-shah** [comment]
Hi Rainer,

Okay. I will push changes on develop and let you know. We will revert this if you do not approve this.

Thanks

**Comment by darshi-shah** [comment]
Hi Rainer,

This is pushed on develop branch. Please revert hk_search feature. Also, please make sure that views_mobile and mobile_detect modules are enabled. 

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 

I don't like it. We need two more modules active for this solution, but then, even when there is enough space for the popup, vital information is missing on mobile, and if there are 12 apartments, we still can't fully see the popup and move it around - it closes when I move it a bit. I still can't imagine why it should be a problem to open the popup in the first place. You need to find the reason for that, I'm afraid.

**Comment by darshi-shah** [comment]
Okay, I will revert these changes and push on develop branch.

**Comment by darshi-shah** [comment]
Hi Rainer,

We checked this and problem is with data. In mobile devices,  since data is more, marker  goes out of mobile screen and that causes popup to close automatically. This worked before with show more/less functionality because in that also when clicked on show more we used to remove some of the fields above table. 

As a solution, we have added a scroll to popup for mobile devices. Since the entire popup has scroll, we have removed scroll from table. 

This solution is working fine for scenarios we tested. We have pushed this in develop branch. Please take pull and we can test on dev site as well. 

Do let us know your views on this.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

I have pushed some changes for this on develop branch. Please take pull. 

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
looks good, closing this.
