### ISSUE TITLE
Clean up theme for better W3C compliance

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#54]
There are a number of old tags in hk_theme that throw errors in the W3C validator that should get fixed, and I added bing webmaster verification that should as well be added: 
- add `<meta name="msvalidate.01" content="39B34C79CB9947373E2134525CD68342" />` just behind google verification tag
- add `<meta name="yandex-verification" content="43592467d515c22c" />` behind bing validation
- get rid of obsolete `profile="<?php print $grddl_profile; ?>"` in head tag
- get rid of cleartype meta tag that is unsupported (see https://www.drupal.org/node/1717090)
- change viewport tag to be more google compliant: `<meta name="viewport" content="width=device-width,initial-scale=1">
`
Also, there is a strange occurence of additional doctype, html and body tags in the first two search box forms: 
```
<form action="/" method="post" id="facetapi-multiselect-form-2" accept-charset="UTF-8"><div><!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<?xml encoding="UTF-8"><html><body><div class="form-item form-type-select form-item-facets">
 <select class="facetapi-multiselect facetapi-multiselect-field-kategorie form-select" multiple name="facets[]" id="edit-facets--2"><option disabled></option><option value="field_kategorie:15">Bezugsfreie Wohnungen (56)</option><option value="field_kategorie:11">Gewerbe Kauf (3)</option><option value="field_kategorie:7">Vermietete Wohnungen (3)</option></select></div></body></html>
<input type="submit" id="edit-submit--2" name="op" value="Abschicken" class="form-submit" /><input type="hidden" name="form_build_id" value="form-g4hptDj7G6u52vfAOcI974jEs8MwN2AoMNjPAhoMuxM" />
<input type="hidden" name="form_id" value="facetapi_multiselect_form_2" />
</div></form>
```
That should be investigated too.

**Comment by darshi-shah** [comment]
Hi Rainer,

First five points are done in hk_theme. Since the changes were applicable in hk_subtheme theme as well, I have made change in hk_subdomain as well. Please take pull on dev.

Last point is due to multiselect in first two facets. Using normal select solves this issue. Let me know if I should change this. 

Thanks
Darshi
