### ISSUE TITLE
Update Drupal Core to 7.53

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#55]
update core and modules:
- advagg
- cdn
- ctools
- entityreference_feeds
- feeds
- i18n
- media
- multiform
- office_hours
- search_api_ranges
- workflow
- wysiwyg

**Comment by heliogabal** [comment]
Drupal 7.53 came out, so we have to upgrade to that version now.

**Comment by darshi-shah** [comment]
Hi Rainer, 

As of now, drupal 7.52 is the latest version. Please check https://www.drupal.org/project/drupal/releases?api_version[]=103

I am attaching screenshot as well. 
![d7-release](https://cloud.githubusercontent.com/assets/15724372/20915431/d4314cf4-bbab-11e6-92fb-b03b9b6b61ba.png)


Thanks
Darshi

**Comment by heliogabal** [comment]
Ah ok, I just read the next release info, so Drupal 7.53 is coming out tomorrow, mixed that up. Sorry for the confusion. So we only need to upgrade that if we experience drag-n-drop problems, otherwise it's fine to wait for the next security release...

**Comment by heliogabal** [comment]
can be pushed to stage.

**Comment by darshi-shah** [comment]
Hi Rainer,

The core is upgraded to 7.53 which came out yesterday.  All upgrades are pushed on develop.

There are couple of other modules which has upgrades. Please see the list below: 
Localization update
Manual Crop
Media(security update required)
Menu block

Let me know if this should be upgraded immediately. 

Thanks
Darshi

**Comment by heliogabal** [comment]
we don't use menu_block. Should do Media, Manual crop, l10n_update and metatag updates though.
