### ISSUE TITLE
Smaller bugfixes and enhancements to admin and Karten view

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#59]
The client found some things he would like to haved changed asap. Some I did already on the live site, we just have to make sure they're also in the features:

Admin view /admin/content/dash/wohnungen:
- get rid of now superfluous states Schattenwohnung in the filters and all other grouped states that don't make sense any more because Schattenwohnung doesn't exist any longer. See live view. Also check in admin/content/dash for objects.
- set state active as standard. Already changed in live view.
- Change table headers according to the live view: Erstellt am, Geändert am for creation and change date. See live view.
- If it's easily done, also align the price field better so the th and td are beginning at the same spot and the price column doesn't collapse onto two lines on desktop and tablet.
- once a state has been selected, and a node has been edited, ideally, the editor should get back to exactly the place where he last was - no idea if this is possible at all, but at least the states shouldn't turn back to default state, possibly also the object id. It's very tedious to always having to reselect and rewait and rescroll while editing. Maybe the "remember last selection" in the filter could do that, but I feel like it doesn't do anything or bugs weirdly.

Karten view: 
- Map popup apartment list: order by apartment no. These seems sometimes to be the case, but in SPE03 you can clearly see it's not.

**Comment by darshi-shah** [comment]
Hi Rainer,

All the changes are done and included in features except for CSS change. You need to revert hk_admin and hk_search.

CSS change would need approx 2-3 hours. Please let me know if I should proceed with this.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, no need to put in more work until the client approves otherwise. So wil close this once it is checked.

**Comment by heliogabal** [comment]
can be pushed to stage.
