### ISSUE TITLE
Research possible PDF exposé creation solution and prepare estimate

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#62]
It's probably something we will start after having the frontpage redesigned, but it can't hurt to start thinking about this early on so we have something else in the pipeline. 

The goal is for an agent to be able to create a PDF exposé of any apartment, or several apartments in one object ideally. Agent should be able to select cover photo and a selection of the photos of object and apartment, because there might be too many photos to include them all and agent needs some editorial flexibility as to which photos to include.

I was thinking of doing this with a new content type "exposé", that can than be (auto-)attached to the respective apartment via entityreference, if it is a single apartment exposé. I started experimenting with the print module together with wkhtmltopdf library to create the PDF.

There is another catch though: we need several versions of the PDF, one to provide for immediate download on the site, and one that has some more information (like ceiling height) the agents can send to clients via the CRM. This one should also print the address of the client from the CRM into the PDF. There also need to be an individual text for every exposé that is sent to a client individually, and of course the sent exposés should be saved to the clients document tab and attached to the apartment in the CRM as well.

So all in all, that's at least a variety of 3 exposé types: 1 apartment for website, 1 apartment for CRM, Several apartments for CRM.

I'll attach some templates for the exposé, to give you an idea how it should look in the end. I already created the content type and installed print and did some testing to create the PDF, but left this alone for a long time, so you would have to figure out the status quo on this and an test what is working and what not.

Any better approach to this would be more than welcome, as I found it quite cumbersome to work with print.

The templates might not exactly work, so they might be changed according to what is technically possible. But it will give you an idea, I hope.

[H+K_Expose_00_Anschreiben.pdf](https://github.com/saurabhd/hk_realestate/files/646064/H.K_Expose_00_Anschreiben.pdf)
[H+K_Expose_01_ErsteSeite.pdf](https://github.com/saurabhd/hk_realestate/files/646059/H.K_Expose_01_ErsteSeite.pdf)
[H+K_Expose_02_Objekt.pdf](https://github.com/saurabhd/hk_realestate/files/646060/H.K_Expose_02_Objekt.pdf)
[H+K_Expose_03_Wohnung.pdf](https://github.com/saurabhd/hk_realestate/files/646062/H.K_Expose_03_Wohnung.pdf)
[H+K_Expose_04_Bilder.pdf](https://github.com/saurabhd/hk_realestate/files/646061/H.K_Expose_04_Bilder.pdf)
[H+K_Expose_05_Lage.pdf](https://github.com/saurabhd/hk_realestate/files/646063/H.K_Expose_05_Lage.pdf)
[H+K_Expose_08_AGB.pdf](https://github.com/saurabhd/hk_realestate/files/646065/H.K_Expose_08_AGB.pdf)

**Comment by darshi-shah** [comment]
Hi Rainer,

Below is my understanding for this along with questions.

We will have 3 PDFs.

- 2 PDFs for apartment
-- 1 PDF available on apartment page to download
-- 1 PDF for CRM
- 1 PDF for object

**PDF on apartment page**

This PDF can be downloaded by anyone who visits the site. This PDF will contain basic information of the apartment along with images. 

Questions:
- Do we need to provide image selection for this PDF creation ? or PDF will contain all images from apartment including floor plan?
- Should this PDF include details and energy consumption details?
- if energy consumption has PDF attached to it?
- Should this PDF include map?


**PDF for CRM**

Agents sends this PDF to users from CRM. This will include user address and more detailed info about apartment. Images will be selected by Agents.
This PDF will show in documents for users and will be attached to apartment as well but will not be accessible by public front end.

Questions:
- Detailed info will include all details we have on apartment ? same as details section on apartment page ?
- Please explain about "There also need to be an individual text for every exposé that is sent to a client individually." 
- Can agents add custom message to each PDF they sent out?
- Should this PDF include map and address?
- Should there be PDF for shadow apartment? If yes, what details it should contain?


**Object PDF**

This PDF will contain details and images from object. It will also include list of all apartments in this object. Image selection will be there. This PDF is attached to object. 

Questions:
- How this PDF will be sent from CRM?
- Should apartment list in this should include shadow apartments?

Please let me know if this understanding is correct. Also,can you please let me know which PDF(from the ones that you attached in initial comment) is applicable in which scenario?

I will be doing some R&D for PDF creation. 

Thanks
Darshi

**Comment by heliogabal** [comment]
> We will have 3 PDFs.
> 
> 2 PDFs for apartment
> -- 1 PDF available on apartment page to download
> -- 1 PDF for CRM
> 1 PDF for object

almost ;-) 

We will have 3 PDFs. All three for apartment(s).
1.) Single apartment PDF for download on the apartment page
2.) Single apartment PDF for sending via CRM
3.) Multiple apartments in one object PDF for sending via CRM

> PDF on apartment page
> 
> This PDF can be downloaded by anyone who visits the site. This PDF will contain basic information of the apartment along with images.

yes. The information also includes values from the object like selection of object images, address, map etc.

> Questions:
> 
> Do we need to provide image selection for this PDF creation ? or PDF will contain all images from apartment including floor plan?

yes, if at all possible, there should be image selection for all three PDFs. Floor plan(s) is/are always included

> Should this PDF include details and energy consumption details?

yes, that's legally binding.

> if energy consumption has PDF attached to it?

no, we only need the data, not the Energieausweis PDF.

> Should this PDF include map?

yes. At a later stage, there should be even two versions of the map, the same as on the page for the downloadeble PDF and an enhanced one (more details, public transport, schools etc.) for the CRM version.

> PDF for CRM
> 
> Agents sends this PDF to users from CRM. This will include user address and more detailed info about apartment. Images will be selected by Agents.
> This PDF will show in documents for users and will be attached to apartment as well but will not be accessible by public front end.

yes.

> Questions:
> 
> Detailed info will include all details we have on apartment ? same as details section on apartment page ?

yes

> Please explain about "There also need to be an individual text for every exposé that is sent to a client individually."

The CRM exposés should be personalized, which means that they are addressed at a contact from the CRM, and there is some personal message that the agent can type that should be printed on the first page of the exposé as seen on H+K_Expose_00_Anschreiben.pdf

> Can agents add custom message to each PDF they sent out?
yes, that's what I meant. Custom message that is a personal note from the agent regarding the previous conversation, or some additional info, printed to 00_Anschreiben

> Should this PDF include map and address?
yes

> Should there be PDF for shadow apartment? If yes, what details it should contain?

As shadow apartments are not shown on the page, there will also not be a downloadable version for everyone. But if an agent sends a CRM exposé, that should be also possible for shadow apartments and can include map and address as well. There is no difference between shadow apartment and normal apartment CRM exposé.

> Object PDF
> 
> This PDF will contain details and images from object. It will also include list of all apartments in this object. Image selection will be there. This PDF is attached to object.

> Questions:
> 
> How this PDF will be sent from CRM?
> Should apartment list in this should include shadow apartments?
> Please let me know if this understanding is correct. Also,can you please let me know which PDF(from the ones that you attached in initial comment) is applicable in which scenario?

This might be a good idea for future improvement, but for now, there should be only the option to create a CRM exposé including multiple apartments. That would include the object data like in the other exposés, then a list of the selected apartments with their basic features (rooms, space, price etc.), followed by the apartment pages as in the single exposés, but with all of the selected apartments. That's also the reason why agent has to be able to select images, as there would be too much  duplication otherwise.

Thinking about it, it might be enough to first create single apartment options, and look at multiple apartments later on. There are many tricky questions involved, and the template PDFs don't reflect cleanly all possibilities, they're rather a mixture of all thinkable cases without definite decision as to which to take. These will likely have to be refined in the process.

So focus on 1) and 2) for now, only keeping in mind that this might be expanded later on with multiple apartments. But the client can decide if he really needs it after having the basic version.

**Comment by darshi-shah** [comment]
Hi Rainer,

Thanks for the information and answers. 

I will start with image selection part and then move to PDF creation.  I will be focusing on option 1 keeping in mind that it will be expanded further to include option 2 and 3 and more.

I will go through PDF module first to see how we can create PDF in desired way and how much customization will be supported. 

I will also check if we can use other libraries to generate PDF.  I will keep you updated on my findings. 

Thanks

**Comment by heliogabal** [comment]
Also won't need that for now, as Propstack can create exposés. So closing.
