### ISSUE TITLE
More cleanup for W3C compliance

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#63]
There are some minor errors in the code that we could quickly fix: https://validator.w3.org/nu/?doc=http%3A%2F%2Faddweb.dev.herbert-kohlmeyer.de%2F 

the language switcher module lacks an additional lang attribute that is required whenever there is a xml:lang attribute existing. Please create a patch and open an issue on d.org to send the patch to.

http://stackoverflow.com/questions/4199832/can-someone-explain-what-the-xmllang-attribute-does-in-html5

Also, in the theme we can get rid of the role="banner" in the <header> tag.

Finally, I think there is no reason to have a <?xml encoding="utf8"> that is hardcoded in facetapi_multiselect - this is a HTML document and not xml. You could also discuss and propose that in the issue queue on d.org

The option and defer errors can be ignored, I would say they are rather cosmetic. W3C validates if the empty option element has a &nbsp; inside instead of being empty, and the defer doesn't make any sense without a src attribute, I guess that's some bug in advagg module, but we don't use the latest version for now, so no use in looking into that for now.

**Comment by darshi-shah** [comment]
Hi Rainer,

The changes are pushed on dev. Please take pull.

For the record, lang attribute issue is reported issue and pending commit :  https://www.drupal.org/node/1904528

For facetapi_multiselect, I have created an issue here : https://www.drupal.org/node/2835107. I will generate a new issue for discussing about <?xml encoding="utf8">.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
thanks for that. Didn't realize there was already an issue for the lang attribute... well then, we can live with it.

Thanks for the issue and patch.
