### ISSUE TITLE
Create Login with Facebook option

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#64]
As we now have a facebook page (https://facebook.com/herbertundkohlmeyer), we would also need to have an option to log in with facebook on the website, similar as the log in with twitter that is already there. This would be the first step for the customer intranet project.

The goal is to ease the registration / login process, and collect data available on the facebook profile of the customer to put into the CRM contact.

Let me know what else you would need for that, and how much time you think this is going to take. I probably should make you facebook admin for the page, so you can have access to the developer section?

**Comment by darshi-shah** [comment]
I will create an app to use on dev site and local environment using dev id. For live site, we will use HK account to create app.

**Comment by heliogabal** [comment]
Ok, sounds good.

**Comment by heliogabal** [comment]
User to CRM contact sync would be good additionally. Possible data:
- Photo
- Age / Birthday
- Name
- Email  
- Address
- Messenger contact
- Occupation

**Comment by darshi-shah** [comment]
CRM user sync is done with agent role. New users created via FB login has buyer role.  Please let me know if we should implement this for normal users as well. 

Also, please note that the fields mentioned in previous comment are present in CRM contact and not in user profile.

**Comment by darshi-shah** [comment]
Hi Rainer,

To get this information from facebook, we will need to get review done first. 

Please refer to screenshot attached. This screenshot is taken from Facebook app I created to use in local environment. 

![hk_local_app_permission](https://cloud.githubusercontent.com/assets/15724372/21313064/9a3c55b0-c615-11e6-9d1d-25b6a58def5b.png)

Also, please refer to https://developers.facebook.com/docs/facebook-login/permissions for more details.

Let me know how we should proceed with this. 


Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 
for now, let's work with what we get without review from the public profile. That's at least the photo, name, email and address, I think? We can always decide to add more info later.

**Comment by darshi-shah** [comment]
Hi Rainer, 

We get name, email and profile picture. I will work on creating CRM contact based on this.

Thanks

**Comment by darshi-shah** [comment]
Hi Rainer, 

CRM contact creation based on FB login is done and pushed on develop. Please take pull and revert hk_social_login feature. 

Thanks
