### ISSUE TITLE
Create customer profile page

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#65]
After having the possibility for customers to log in with twitter and facebook, they should land on their profile page where they can see the information gathered about them, including the possibility to edit their profile. Much like the CRM pages, with the same design. They should also have access to their activity and favorites tabs from there.

Next step would be to also have a documents tab, where they can see exposés and other documents provided for them, and the possibility to upload documents themselves. I still need the full list of all possible documents, but I think this could be prepared beforehand. For example, according to German law, we need a copy of their ID to prevent money laundering.

**Comment by darshi-shah** [comment]
Hi Rainer,

On user profile page, should we show CRM contact details of the user? This includes address, contact details etc. If yes, should we allow users to edit their CRM contact profile along with user profile ?

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
yes, we should show all the data to the user with the ability to edit both.

**Comment by darshi-shah** [comment]
Hi Rainer,

This is deployed on dev site. Please check. 
We created a new user on dev and added activities and notes for this user. Please check here : http://addweb.dev.herbert-kohlmeyer.de/users/johnnythree-harper. 

Please let us know your feedback.

Also, users registering via FB gets buyer role by default while if user registers normally they do not get buyer role. In this case, they do not see tabs on their profile page. Should we assign buyer role to them by default or should the role be assigned when they first make an inquiry? Please confirm.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, I'll have to check by creating a new user myself. 

Yes, FB users should get the buyer role auto-assigned as well.

**Comment by darshi-shah** [comment]
Hi Rainer,

I meant the normal user registration. Users registered via FB gets buyer role by default. Users registering normally get authenticated user role only. Should we assign them buyer role as soon as they register or when they make an inquiry?

Thanks

**Comment by heliogabal** [comment]
ah, I see. Yes, buyer role would be good as soon as they register.

**Comment by darshi-shah** [comment]
Hi Rainer,

This is deployed on live. Can we close this issue? 

Thanks

**Comment by heliogabal** [comment]
Yes, closing.
