### ISSUE TITLE
Update SMTP module

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#66]
There is a major security issue with the phpmailer library included in the smtp module. Therefor, we need to update the module asap.

**Comment by darshi-shah** [comment]
Hi Rainer,

The update is pushed on the develop branch. Please take pull. 

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, can you change the email addresses, where inquiry mails are sent to to yours and / or mine, and check sending of mails with the new version? Then we can push this to stage and live.

**Comment by darshi-shah** [comment]
Hi Rainer, 

The emails are changed to youd email id and mine. I have checked that emails are going through.

Thanks

**Comment by darshi-shah** [comment]
Hi Rainer,

This is deployed on live. Can we close this issue? 

Thanks
