### ISSUE TITLE
Update fontfaceobserver library to version 2.0.7

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#67]
We need the latest version of the fontfaceobserver library, found here: https://github.com/bramstein/fontfaceobserver/releases 

Please update for all three branches. As this is a minor issue, we can push that together with other things, so we don't have to do the whole cycle just for this change.

**Comment by darshi-shah** [comment]
Hi Rainer,

This is pushed on develop.

Thanks

**Comment by heliogabal** [comment]
You can theoretically push this to stage, but as we don't use advagg temporarily on live, we could also just hold it for now.

**Comment by darshi-shah** [comment]
Hi Rainer,

This is deployed on live though it will not make any difference as module is disabled.  Can we close this issue? 

Thanks

**Comment by heliogabal** [comment]
Yes, closing this. It will be déactiver with the next Version of advagg, that fixes the nocss Pages hopefully.
