### ISSUE TITLE
Aegir and jenkins integration

### ISSUE THREAD

**Issue by darshi-shah** [saurabhd/hk_realestate#68]
Hi Rainer,

I have passed on all the details you provided to our dev-ops person. I will keep you posted on the progress here. 

Please check ssh credentials you provided. I am unable to login with them.

Thanks

**Comment by heliogabal** [comment]
As omega8 told me that they are going to introduce opendevshop (http://opendevshop.com/) support to their hosting in February, we should wait until this happens and use that for our git workflow. Closing this therefore.
