### ISSUE TITLE
Bug fixing CRM

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#69]
Hi Darshi, 
I revisited the CRM on prod, and there are still a few glitches that (re-)surfaced and need polishing:

- Add meeting and Add task titles of the icons on agent central are not translated and not translatable even after refreshing strings, but they're correct on /search
- When I click on "Add meeting" on agent central and close the popup again, the icons get displaced:
![auswahl_037](https://cloud.githubusercontent.com/assets/389844/21669138/39d8a9f2-d309-11e6-8c3e-08192e55b132.png)
- On the Send email popup, the email type selects are not translatable, the taxonomy says "no translatable fields"
- The Inquiry and Participants fields mustn't be shown (that's true for all popups)
- the CRM menu item should point to /search instead of /crm-core
- there's also some discrepancies between /search and /agent-central: The links to create new contacts and activities is right on /search and should be equally adapted to agent-central. The Logo and links are sitting too much on top on /search, especially for the roles that also have the admin_menu visible. Should match agent central.
![auswahl_038](https://cloud.githubusercontent.com/assets/389844/21669674/1b4b2924-d30e-11e6-979a-37daea9beeaf.png)

I want to introduce the CRM soon, so if would be good to fix these before. I will add more things I find while testing here.

**Comment by darshi-shah** [comment]
Hi Rainer,

Point 1,2,5 and 6 are pushed on develop. Please take pull. I will be working on rest of the issues. 

Thanks

**Comment by darshi-shah** [comment]
The Inquiry and Participants fields mustn't be shown (that's true for all popups)
- check to hide these fields if they are pre-filled.

**Comment by heliogabal** [comment]
thanks, I pulled the changes. no feature revert done though.

**Comment by darshi-shah** [comment]
Hi Rainer, 

Translations are pushed on dev site. Please take pull .

Thanks

**Comment by darshi-shah** [comment]
Hi Rainer,

This is already deploy on live site. Can we close this issue? 

Thanks
