### ISSUE TITLE
Unstyled content on prod backend

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#70]
There is also this weird bug on prod that shows up occasionally, where an advagg bundled file is not found. They seem to have a redirect_counter=6 in common, looks like that: 

> contact:19 GET https://herbert-kohlmeyer.de/sites/herbert-kohlmeyer.de/files/advagg_css/cs…901Pqs__FcvyHMtE7GxYyKB-fbnGQqgcGst75BYjK8dzRTupf9k.css?redirect_counter=6 
contact:68 GET https://herbert-kohlmeyer.de/sites/herbert-kohlmeyer.de/files/advagg_js/js_…MzwRN3k__FcvyHMtE7GxYyKB-fbnGQqgcGst75BYjK8dzRTupf9k.js?redirect_counter=6 
contact:25 GET https://herbert-kohlmeyer.de/sites/herbert-kohlmeyer.de/files/advagg_css/cs…9hb0Ak__FcvyHMtE7GxYyKB-fbnGQqgcGst75BYjK8dzRTupf9k.css?redirect_counter=6 
contact:68 GET https://herbert-kohlmeyer.de/sites/herbert-kohlmeyer.de/files/advagg_js/js_…MzwRN3k__FcvyHMtE7GxYyKB-fbnGQqgcGst75BYjK8dzRTupf9k.js?redirect_counter=6

After some random reloading, the correct files are mostly loaded. If you find some time and don't know what to do, you could have a look at that, but don't waste too much time, as I suspect it either being a bug in advagg (were still using an older version bundled with omega8, I think), or with their caching / redis going nuts. But if you have any idea what could be the cause of this, it would make the editor experience much more pleasant and reliable...

**Comment by darshi-shah** [comment]
Check version  2.20 first.

**Comment by darshi-shah** [comment]
Hi Rainer,

The module is upgraded to 2.20 and pushed to develop. Please take pull. We need to check this bug on dev or live. 

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
pulled and cc alled.

**Comment by heliogabal** [comment]
unfortunately that didn't solve the problem. You will have to investigate further on that.

**Comment by heliogabal** [comment]
I disabled the advagg module for now until there is a new version used by omega8. So closing this for now.
