### ISSUE TITLE
Make search box toggable on all static pages via the search icon

### ISSUE THREAD

**Issue by arpita-addweb** [saurabhd/hk_realestate#8]
**Site Area** : all pages except frontpage / search views (/buy, /buy/freehold-apartments, /buy/capital-investment, /buy/commercial-property-sale)

**Priority** : Low

**Description** : The search box is only toggable via the search icon top right on the frontpage and the buy page and subpages. It should appear on all other pages as well, when you click on the icon (slide in on top of the page, like on the buy page). Once you select a value, you should be taken to the buy page showing the results.I had to use some nasty tricks to be able to provide the search box on non-search-pages, if I recall correctly. Can't find the issue with the proposed solution, and there are several issues that touch the problem, mostly fixed now.

**Comment by vivek-addweb** [comment]
Hi 
Do you need toggle Search box functionality for Desktop or only Mobile for all pages?

**Comment by heliogabal** [comment]
Hi Vivek, 
this issue was meant for Desktop. It's basically the same for mobile (see #2), except that on the mobile frontpage, the search box should be initially hidden. But apart from that, the behaviour of clicking the magnifiying glass icon should be consistent. I'm not sure if I described it enough, so please ask me if you need clarification.

**Comment by darshi-shah** [comment]
Hi Rainer,

Can you please let me know how search facets are placed on pages? It seems that they are not using block configurations. 

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, 
Unfortunately, I can't really tell you. I vaguely remember that there was an issue to have the facets on non-search-pages (like the map) on drupal.org and I experimented with that solution, but later it was not needed any more, so I removed that again. It was quite tricky to get it to work, but once it did, I forgot about it. If I look at it now, I can't find it anywhere in the site where this could be defined... Sorry about that, but let me know when you find out how it is done ;-) Possibly helpfull:

https://www.drupal.org/node/2017007 
Good luck!

**Comment by darshi-shah** [comment]
Hi Rainer,

We used facets blocks to show search filters on non search pages. The look like this : http://i.share.pho.to/3fe69c43_o.png

We are going to change the look and make this dropdown using jquery so that it matches filters on homepage and buy pages. 

Let me know any concerns regarding this.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 

if that works better and it is not too much work (what do you guess?), than I don't mind if you make the behavior more robust and change it.

thanks, 
Rainer

**Comment by darshi-shah** [comment]
Hi Rainer, 

Thanks for confirming this.  Just to confirm, users will be redirected to buy page once they select filter. They will see search result for filter they selected. 

Thanks
Darshi

**Comment by heliogabal** [comment]
yep, that's exactly how it should be.

**Comment by darshi-shah** [comment]
Hi Rainer,

Please do following steps : 

1 - take pull

2 - enable feature "hk_custom_search".

3 - Go to "admin/structure/views/view/karten/edit" add facets block with following settings : 
     - Block name:facets borough block
     - search page path:buy
     - Facet field:Borough

4 - Add another facet block in same view with follwing settings and save view :
     - Block name:Facets Category block
     - Search page path:buy
     - Facet field:Category

5 - go to "admin/structure/block" and configure "facets borough block" and "Facets Category block" to show in "search" region with visibility on all pages except following pages :
<front>
buy
buy/*

Clear cache and see search filters on non-search pages. 

Please note that the node count for apartments is not showing correct count on some of the filters. We are working on fixing this. 

Please let me know any other question in this.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

Please take pull and check this functionality. Counts are corrected.

Thanks
Darshi

**Comment by darshi-shah** [comment]
Hi Rainer,

Please take pull and enable "hk_custom_search"  feature.

Let us know your feedback.

Thanks
Darshi

**Comment by heliogabal** [comment]
I get a title for the category block that shouldn't be there. Can this be incorporated in the feature/module or do I have to change this manually all the time?

![auswahl_026](https://cloud.githubusercontent.com/assets/389844/17362215/65b4b9ee-5974-11e6-9b2e-ae9410d6732c.png)

**Comment by heliogabal** [comment]
I know I said this should show on all pages but front/buy pages, but now that it does, I realize there are certainly some pages where it shouldn't show:
user
search
search/*
apartment and object nodes

will update this list as I come along other pages...

Maybe it is easier to positively mark pages where the search bar should be shown: 
service
service/*
ueber-uns
ueber-uns/*
kontakt
kontakt/*
oeffnungszeiten
impressum
datenschutzerklaerung
allgemeine-geschaeftsbedingungen-agb
widerrufsbelehrung
jobs
(and their english equivilents...)

**Comment by heliogabal** [comment]
toggle function seems to have been broken somewhere in between...

**Comment by heliogabal** [comment]
Also, the initial state of the facet blocks should be hidden on all these pages, and only get toggled to visibility once the search icon is clicked.

**Comment by darshi-shah** [comment]
Hi Rainer, These changes are done and pushed on dev branch. Please make sure hk_custom_Search is enabled.

**Comment by darshi-shah** [comment]
Hi Rainer, 

This is fixed, Can we close this please ?

Thanks
Darshi

**Comment by heliogabal** [comment]
yep, closing,
