### ISSUE TITLE
apartment missing from the map (LIVE)

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#84]
Hi Darshi, 

I have another weird thing... this apartment seems to be perfectly like the others, and the object has it's address set and all, but it won't shop on the frontpage map:

https://herbert-kohlmeyer.de/kad12/2-zimmer-wohnung-denkmalensemble-weberwiese

could you please have a look? Don't spend too much time (1-2h), but if you could find something by that time, that would be great.

**Comment by darshi-shah** [comment]
Hi Rainer,

This is fixed on live site. 

Apartment has field called shadow apartment. This field with needs to have value. Keeping this blank cause apartment to not show on map. 

Thanks

**Comment by heliogabal** [comment]
thanks!

**Comment by heliogabal** [comment]
This bit us once again as Lutz was trying to publish an apartment and it didn't show on the map. We should make the fields for Schattenobjekt and Schattenwohnung mandatory therefore, to make sure it is filled in and the apartment is shown on the map. 

I Did that already on Live, please make sure you do that on dev branch and feature as well, so we don't get a regression later on.

**Comment by darshi-shah** [comment]
Hi Rainer,

I would approx need 3-4 hours to fix this.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi,
what could take 3-4h to do that? Don't you just have to set the fields to mandatory (2 clicks) and recreate the feature?

**Comment by darshi-shah** [comment]
Hi Rainer,

This seem to be mistake from my end. I will do this and push on develop.

Thanks

**Comment by heliogabal** [comment]
Hi Darshi, I was just wondering...

**Comment by darshi-shah** [comment]
This is done.
