### ISSUE TITLE
Post to twitter with text and media

### ISSUE THREAD

**Issue by darshi-shah** [saurabhd/hk_realestate#88]
Posting to twitter is implemented for object content type. Currently, title and link is shared on twitter. We need to add an image and the text from [node:field_object_txt_map_popup] to twitter post. 

Ref : https://www.drupal.org/node/1981472
Check twitter cards as well.

**Comment by heliogabal** [comment]
Hi Darshi, 
I managed to implement this, just had to use the metatag twitter card submodule and configure it correctly. Now we have beautiful images on Twitter!

Therefore closing this.
