### ISSUE TITLE
Sidetask... change some csv creation logic

### ISSUE THREAD

**Issue by heliogabal** [saurabhd/hk_realestate#90]
Hi Darshi!
Here are the files and description as to what has to be done (had to change the csv to txt in order to upload):
[1.2.-14.2.2017.csv.txt](https://github.com/saurabhd/hk_realestate/files/830952/1.2.-14.2.2017.csv.txt)
[1. Originaldatei Februar.csv.txt](https://github.com/saurabhd/hk_realestate/files/830953/1.Originaldatei.Februar.csv.txt)

the first file is the one how it should be, and the second one the original. So there has to be an additional column KST added, that gets filled depending on in which country the invoice is declared for, and if there is a VAT number (USt.-ID) provided for countries inside the EU. See 2)

1) The column DEBITOR should now always be 69988
2) When the Konto is 8400, the KST is 30013, when the Konto is either 8150 or 8336, the KST is 50013. The Konto is 8400 when the order is inside Germany or the EU, but no VAT number provided, 8150 when it is outside of the EU (that includes Switzerland). And 8336, if it is inside the EU, but a VAT number is declared. I think this is already in place in line 273 to 298, can you have a look and verify that?
3) Can you add the columns KST to the csv, and add the conditions as outlined in 2)?

The concerned file is DATE_orders_datev.csv and it gets created in exportCSV.php, starting with line 255:
[exportCSV.php.txt](https://github.com/saurabhd/hk_realestate/files/830993/exportCSV.php.txt)

**Comment by darshi-shah** [comment]
Hi Rainer, 

8336 is not used anywhere in exportCSV.php.  Can you please confirm this state for konto needs to be introduced? 

Thanks

**Comment by darshi-shah** [comment]
Hi Rainer,

Please see attached file. Let me know if any change needs to be done in it. I took 1.5 hours to complete this.

Thanks
[exportCSV.php.txt](https://github.com/saurabhd/hk_realestate/files/833932/exportCSV.php.txt)

[sidetask.diff.txt](https://github.com/saurabhd/hk_realestate/files/833948/sidetask.diff.txt)
